#!/usr/bin/env python3
"""Svec Studio Icons — freedesktop icon pack pro Fedoru / KDE Plasma.

Vygeneruje tři varianty icon themu:

  SvecStudio-Accent  (v2)   — obrysy `currentColor` + `ColorScheme-Accent`
                              → Plasma/KDE přebarví podle akcentní barvy systému;
                              mimo KDE renderuje fallback `#3daee9` (Breeze blue)
  SvecStudio-White   (v1.1) — pevně bílé obrysy
  SvecStudio-Black   (v1.2) — pevně černé obrysy

Zdroje:
  src/*.svg   → zdrojové ikony (svec-<name>.svg) → scalable/apps/
  logo.svg    → logo Svec Studia (cz.svec.Studio, svec-studio — barevné)
  FDO_MAP     → standardní freedesktop jména (apps/places/actions/…)

Použití:
  python3 build.py              # → themes/SvecStudio-*/
  python3 build.py --install    # + ~/.local/share/icons/
"""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC_DIR = ROOT / "src"
LOGO_SVG = ROOT / "logo.svg"
DEFAULT_OUT = ROOT / "themes"
INSTALL_DIR = Path.home() / ".local" / "share" / "icons"

ACCENT_FALLBACK = "#3daee9"  # Breeze blue — render mimo KDE
WHITE = "#ffffff"
BLACK = "#000000"

VARIANTS = {
    "SvecStudio-Accent": {
        "label": "Accent",
        "version": "2",
        "comment": "Outline icons from Svec Studio — recolored by Plasma accent color",
        "follows_color_scheme": True,  # KDE: bez tohoto klíče KIconLoader ColorScheme-* nenahrazuje
    },
    "SvecStudio-White": {
        "label": "White",
        "version": "1.1",
        "comment": "Outline icons from Svec Studio — fixed white",
    },
    "SvecStudio-Black": {
        "label": "Black",
        "version": "1.2",
        "comment": "Outline icons from Svec Studio — fixed black",
    },
}

CCS_STYLE = (
    '<style id="current-color-scheme" type="text/css">'
    ".ColorScheme-Accent{color:%s;}"
    ".ColorScheme-Text{color:%s;}"
    "</style>" % (ACCENT_FALLBACK, ACCENT_FALLBACK)
)

APP_PREFIX = "svec-"
SHORTCUT_PREFIX = "svec-sc-"
KIT_PREFIX = "svec-kit-"

# Standardní freedesktop jména → svec-* zdroj. Po aktivaci thematu se ikony
# použijí systémově (plocha, Dolphin, Kickoff, panely, MIME typy).
# Klíč = kontextový adresář, hodnota = {fdo_jméno: svec zdroj}.
FDO_MAP: dict[str, dict[str, str]] = {
    "apps": {
        # kickoff kategorie + obecné
        "applications-internet": "svec-web",
        "applications-office": "svec-docs",
        "applications-graphics": "svec-image",
        "applications-multimedia": "svec-video",
        "applications-games": "svec-sc-device-gamepad-2",
        "applications-development": "svec-code",
        "applications-system": "svec-desktop",
        "applications-utilities": "svec-tools",
        "applications-accessories": "svec-tools",
        "applications-education": "svec-learn",
        "applications-science": "svec-sc-atom",
        "applications-engineering": "svec-cad",
        "applications-electronics": "svec-sc-cpu",
        "preferences-desktop-personal": "svec-sc-user",
        "applications-other": "svec-extapp",
        "application-x-executable": "svec-extapp",
        "application-x-ms-dos-executable": "svec-extapp",
        "application-x-desktop": "svec-extapp",
        "accessories-text-editor": "svec-writer",
        "text-editor": "svec-writer",
        "accessories-calculator": "svec-sc-calculator",
        "accessories-dictionary": "svec-sc-book",
        "accessories-character-map": "svec-sc-typography",
        "accessories-photo-viewer": "svec-sc-photo",
        "system-file-manager": "svec-sc-folder",
        "file-manager": "svec-sc-folder",
        "system-search": "svec-sc-search",
        "system-users": "svec-sc-users",
        "system-software-install": "svec-sc-package",
        "system-software-update": "svec-sc-cloud-download",
        "preferences-system": "svec-settings",
        "preferences-other": "svec-settings",
        "preferences-desktop": "svec-design",
        "preferences-desktop-theme": "svec-sc-palette",
        "preferences-desktop-icons": "svec-sc-layout-grid",
        "preferences-desktop-wallpaper": "svec-sc-photo",
        "preferences-desktop-color": "svec-sc-color-picker",
        "preferences-desktop-font": "svec-sc-typography",
        "preferences-desktop-display": "svec-sc-device-desktop",
        "preferences-desktop-display-randr": "svec-sc-device-desktop",
        "preferences-desktop-locale": "svec-sc-language",
        "preferences-desktop-keyboard": "svec-sc-keyboard",
        "preferences-desktop-mouse": "svec-sc-pointer",
        "preferences-desktop-accessibility": "svec-sc-accessible",
        "preferences-desktop-notifications": "svec-sc-bell",
        "preferences-system-power": "svec-sc-bolt",
        "preferences-system-network": "svec-sc-wifi",
        "preferences-system-time": "svec-sc-clock",
        "preferences-system-privacy": "svec-sc-shield-check",
        "preferences-system-user": "svec-sc-user",
        "preferences-system-windows": "svec-sc-layout-grid",
        "preferences-kde-connect": "svec-sc-device-mobile",
        "utilities-terminal": "svec-terminal",
        "utilities-system-monitor": "svec-sc-activity",
        "web-browser": "svec-web",
        "internet-web-browser": "svec-web",
        "internet-mail": "svec-mail",
        "mail-client": "svec-mail",
        "image-viewer": "svec-image",
        "document-viewer": "svec-docs",
        "archive-manager": "svec-archiv",
        "multimedia-player": "svec-video",
        "multimedia-audio-player": "svec-music",
        "remote-desktop": "svec-sc-cast",
        "help-contents": "svec-sc-help",
        "help-browser": "svec-sc-help",
        "help-about": "svec-sc-info-circle",
        "system-help": "svec-sc-help",
        # KDE Plasma / KDE apps
        "systemsettings": "svec-settings",
        "org.kde.systemsettings": "svec-settings",
        "org.kde.dolphin": "svec-sc-folder",
        "dolphin": "svec-sc-folder",
        "org.kde.konsole": "svec-terminal",
        "konsole": "svec-terminal",
        "org.kde.yakuake": "svec-terminal",
        "org.kde.kate": "svec-writer",
        "kate": "svec-writer",
        "org.kde.kwrite": "svec-writer",
        "kwrite": "svec-writer",
        "org.kde.ark": "svec-archiv",
        "ark": "svec-archiv",
        "org.kde.gwenview": "svec-sc-photo",
        "gwenview": "svec-sc-photo",
        "org.kde.okular": "svec-docs",
        "okular": "svec-docs",
        "org.kde.spectacle": "svec-sc-aperture",
        "spectacle": "svec-sc-aperture",
        "org.kde.discover": "svec-sc-package",
        "discover": "svec-sc-package",
        "org.kde.plasma-systemmonitor": "svec-sc-activity",
        "plasma-systemmonitor": "svec-sc-activity",
        "ksysguard": "svec-sc-activity",
        "org.kde.kinfocenter": "svec-sc-cpu",
        "kinfocenter": "svec-sc-cpu",
        "org.kde.kwalletmanager5": "svec-sc-wallet",
        "kwalletmanager": "svec-sc-wallet",
        "org.kde.kleopatra": "svec-sc-certificate",
        "kleopatra": "svec-sc-certificate",
        "org.kde.kmousetool": "svec-sc-pointer",
        "org.kde.kcharselect": "svec-sc-typography",
        "kcharselect": "svec-sc-typography",
        "org.kde.kcalc": "svec-sc-calculator",
        "kcalc": "svec-sc-calculator",
        "org.kde.kclock": "svec-sc-alarm",
        "org.kde.kweather": "svec-sc-cloud",
        "org.kde.itinerary": "svec-sc-map-pin",
        "org.kde.kpublictransport": "svec-sc-train",
        "org.kde.qrca": "svec-sc-qrcode",
        "org.kde.francis": "svec-sc-timer",
        "org.kde.keysmith": "svec-sc-key",
        "org.kde.haruna": "svec-sc-movie",
        "haruna": "svec-sc-movie",
        "org.kde.elisa": "svec-music",
        "elisa": "svec-music",
        "org.kde.kasts": "svec-sc-rss",
        "org.kde.recorder": "svec-sc-microphone",
        "org.kde.kwave": "svec-sc-waveform",
        "org.kde.kmix": "svec-sc-adjustments-horizontal",
        "kmix": "svec-sc-adjustments-horizontal",
        "org.kde.kdenlive": "svec-sc-clapperboard",
        "kdenlive": "svec-sc-clapperboard",
        "org.kde.kolourpaint": "svec-sc-palette",
        "kolourpaint": "svec-sc-palette",
        "org.kde.krita": "svec-sc-brush",
        "krita": "svec-sc-brush",
        "org.kde.karbon": "svec-sc-vector-bezier",
        "karbon": "svec-sc-vector-bezier",
        "org.kde.digikam": "svec-sc-camera",
        "digikam": "svec-sc-camera",
        "org.kde.kid3": "svec-sc-tag",
        "kid3": "svec-sc-tag",
        "org.kde.juk": "svec-music",
        "org.kde.kget": "svec-sc-download",
        "org.kde.ktorrent": "svec-sc-download",
        "org.kde.krdc": "svec-sc-cast",
        "krdc": "svec-sc-cast",
        "org.kde.krfb": "svec-sc-cast",
        "org.kde.konversation": "svec-sc-messages",
        "org.kde.neochat": "svec-sc-messages",
        "org.kde.tokodon": "svec-sc-messages",
        "org.kde.kmail": "svec-mail",
        "kmail": "svec-mail",
        "org.kde.kontact": "svec-mail",
        "org.kde.korganizer": "svec-calendar",
        "korganizer": "svec-calendar",
        "org.kde.merkuro": "svec-calendar",
        "org.kde.kaddressbook": "svec-sc-address-book",
        "kaddressbook": "svec-sc-address-book",
        "org.kde.akregator": "svec-sc-rss",
        "akregator": "svec-sc-rss",
        "org.kde.falkon": "svec-web",
        "falkon": "svec-web",
        "konqueror": "svec-web",
        "org.kde.konqueror": "svec-web",
        "org.kde.kdevelop": "svec-code",
        "kdevelop": "svec-code",
        "org.kde.umbrello": "svec-schema",
        "umbrello": "svec-schema",
        "org.kde.kompare": "svec-sc-git-branch",
        "kompare": "svec-sc-git-branch",
        "org.kde.cervisia": "svec-sc-git-branch",
        "org.kde.lokalize": "svec-sc-translate",
        "org.kde.kapptemplate": "svec-sc-components",
        "org.kde.kcachegrind": "svec-sc-activity",
        "org.kde.filelight": "svec-sc-chart-pie",
        "filelight": "svec-sc-chart-pie",
        "org.kde.partitionmanager": "svec-sc-device-floppy",
        "partitionmanager": "svec-sc-device-floppy",
        "org.kde.sweeper": "svec-sc-trash",
        "sweeper": "svec-sc-trash",
        "org.kde.drkonqi": "svec-sc-bug",
        "org.kde.kdebugsettings": "svec-sc-bug",
        "org.kde.ksystemlog": "svec-sc-list-details",
        "ksystemlog": "svec-sc-list-details",
        "kdf": "svec-sc-database",
        "kwikdisk": "svec-sc-database",
        "org.kde.kmenuedit": "svec-tools",
        "kmenuedit": "svec-tools",
        "org.kde.skanlite": "svec-sc-scan-eye",
        "skanlite": "svec-sc-scan-eye",
        "skanpage": "svec-sc-scan-eye",
        "org.kde.kamoso": "svec-sc-camera",
        "kamoso": "svec-sc-camera",
        "org.kde.marknote": "svec-sc-note",
        "org.kde.ghostwriter": "svec-markdown",
        "ghostwriter": "svec-markdown",
        "org.kde.plasma-welcome": "svec-sc-handshake",
        "org.kde.kup": "svec-backups",
        "org.kde.blinken": "svec-sc-bulb",
        "org.kde.kanagram": "svec-sc-abc",
        "org.kde.khangman": "svec-sc-abc",
        "org.kde.klettres": "svec-sc-abc",
        "org.kde.parley": "svec-sc-translate",
        "org.kde.kiten": "svec-sc-book",
        "kiten": "svec-sc-book",
        "org.kde.kgeography": "svec-sc-map-pin",
        "org.kde.marble": "svec-web",
        "marble": "svec-web",
        "org.kde.kstars": "svec-sc-telescope",
        "kstars": "svec-sc-telescope",
        "org.kde.kalzium": "svec-sc-atom",
        "org.kde.step": "svec-sc-atom",
        "org.kde.kalgebra": "svec-sc-math-function",
        "org.kde.kmplot": "svec-sc-chart-line",
        "org.kde.kbruch": "svec-sc-calculator",
        "org.kde.ktouch": "svec-sc-keyboard",
        "org.kde.minuet": "svec-music",
        "org.kde.kturtle": "svec-sc-turtle",
        "org.kde.rocs": "svec-infoflowlab",
        "org.kde.kig": "svec-sc-ruler-2",
        "org.kde.cantor": "svec-sc-math-function",
        "org.kde.labplot": "svec-sc-chart-line",
        "org.kde.artikulate": "svec-sc-microphone",
        # KDE hry
        "org.kde.knights": "svec-sc-chess",
        "knights": "svec-sc-chess",
        "org.kde.kreversi": "svec-go",
        "kreversi": "svec-go",
        "org.kde.bovo": "svec-piskvorky",
        "bovo": "svec-piskvorky",
        "org.kde.kpat": "svec-sc-cards",
        "kpat": "svec-sc-cards",
        "org.kde.kmahjongg": "svec-sc-cards",
        "kmahjongg": "svec-sc-cards",
        "org.kde.kshisen": "svec-sc-cards",
        "org.kde.kmines": "svec-sc-flag",
        "kmines": "svec-sc-flag",
        "org.kde.ksudoku": "svec-sc-layout-grid",
        "ksudoku": "svec-sc-layout-grid",
        "org.kde.ksquares": "svec-sc-layout-grid",
        "org.kde.picmi": "svec-sc-layout-grid",
        "org.kde.kfourinline": "svec-sc-layout-grid",
        "org.kde.kblocks": "svec-sc-components",
        "org.kde.palapeli": "svec-sc-puzzle",
        "palapeli": "svec-sc-puzzle",
        "org.kde.kdiamond": "svec-sc-diamond",
        "kdiamond": "svec-sc-diamond",
        "org.kde.kiriki": "svec-sc-dice",
        "kiriki": "svec-sc-dice",
        "org.kde.kspaceduel": "svec-sc-rocket",
        "org.kde.killbots": "svec-sc-robot",
        "org.kde.katomic": "svec-sc-atom",
        "org.kde.kblackbox": "svec-sc-box",
        "org.kde.knetwalk": "svec-sc-cable",
        "org.kde.knavalbattle": "svec-sc-ship",
        "org.kde.kolf": "svec-sc-flag",
        "org.kde.kbounce": "svec-sc-circle",
        "org.kde.ktuberling": "svec-sc-mood-smile",
        "org.kde.kjumpingcube": "svec-sc-box",
        "org.kde.kbreakout": "svec-sc-square",
        "org.kde.granatier": "svec-sc-device-gamepad-2",
        "org.kde.kapman": "svec-sc-device-gamepad-2",
        # GNOME
        "org.gnome.Nautilus": "svec-sc-folder",
        "nautilus": "svec-sc-folder",
        "org.gnome.Terminal": "svec-terminal",
        "gnome-terminal": "svec-terminal",
        "org.gnome.TextEditor": "svec-writer",
        "gnome-text-editor": "svec-writer",
        "gedit": "svec-writer",
        "org.gnome.gedit": "svec-writer",
        "org.gnome.eog": "svec-sc-photo",
        "eog": "svec-sc-photo",
        "org.gnome.Evince": "svec-docs",
        "evince": "svec-docs",
        "org.gnome.FileRoller": "svec-archiv",
        "file-roller": "svec-archiv",
        "org.gnome.Software": "svec-sc-shopping-bag",
        "gnome-software": "svec-sc-shopping-bag",
        "org.gnome.Calendar": "svec-calendar",
        "gnome-calendar": "svec-calendar",
        "org.gnome.Contacts": "svec-sc-address-book",
        "gnome-contacts": "svec-sc-address-book",
        "org.gnome.clocks": "svec-sc-alarm",
        "gnome-clocks": "svec-sc-alarm",
        "org.gnome.Weather": "svec-sc-cloud",
        "org.gnome.Maps": "svec-maps",
        "gnome-maps": "svec-maps",
        "org.gnome.Totem": "svec-sc-movie",
        "totem": "svec-sc-movie",
        "org.gnome.Rhythmbox3": "svec-music",
        "rhythmbox": "svec-music",
        "org.gnome.Music": "svec-music",
        "org.gnome.Photos": "svec-sc-photo",
        "org.gnome.Epiphany": "svec-web",
        "epiphany": "svec-web",
        "org.gnome.Evolution": "svec-mail",
        "evolution": "svec-mail",
        "org.gnome.Geary": "svec-mail",
        "org.gnome.Calculator": "svec-sc-calculator",
        "gnome-calculator": "svec-sc-calculator",
        "org.gnome.DiskUtility": "svec-sc-database",
        "gnome-disks": "svec-sc-database",
        "org.gnome.baobab": "svec-sc-chart-pie",
        "baobab": "svec-sc-chart-pie",
        "org.gnome.Logs": "svec-sc-list-details",
        "gnome-logs": "svec-sc-list-details",
        "org.gnome.SystemMonitor": "svec-sc-activity",
        "gnome-system-monitor": "svec-sc-activity",
        "org.gnome.Screenshot": "svec-sc-camera",
        "org.gnome.Cheese": "svec-sc-camera",
        "org.gnome.font-viewer": "svec-sc-typography",
        "gnome-font-viewer": "svec-sc-typography",
        "org.gnome.Characters": "svec-sc-typography",
        "gucharmap": "svec-sc-typography",
        "org.gnome.dconf-editor": "svec-settings",
        "dconf-editor": "svec-settings",
        "org.gnome.seahorse": "svec-sc-key",
        "seahorse": "svec-sc-key",
        "org.gnome.Usage": "svec-sc-chart-pie",
        "org.gnome.PowerStats": "svec-sc-bolt",
        "org.gnome.tweaks": "svec-sc-adjustments-horizontal",
        "gnome-tweaks": "svec-sc-adjustments-horizontal",
        "org.gnome.Extensions": "svec-sc-puzzle",
        "org.gnome.Boxes": "svec-sc-box",
        "gnome-boxes": "svec-sc-box",
        "org.gnome.Builder": "svec-code",
        "org.gnome.meld": "svec-sc-git-branch",
        "meld": "svec-sc-git-branch",
        "org.gnome.SimpleScan": "svec-sc-scan-eye",
        "simple-scan": "svec-sc-scan-eye",
        "org.gnome.SoundRecorder": "svec-sc-microphone",
        "org.gnome.Shotwell": "svec-sc-photo",
        "shotwell": "svec-sc-photo",
        "org.gnome.Podcasts": "svec-sc-rss",
        "org.gnome.Polari": "svec-sc-messages",
        "org.gnome.Connections": "svec-sc-cast",
        "gnome-mines": "svec-sc-flag",
        "org.gnome.Mines": "svec-sc-flag",
        "gnome-sudoku": "svec-sc-layout-grid",
        "org.gnome.Sudoku": "svec-sc-layout-grid",
        "gnome-mahjongg": "svec-sc-cards",
        "gnome-chess": "svec-sc-chess",
        "org.gnome.Chess": "svec-sc-chess",
        "quadrapassel": "svec-sc-components",
        "aisleriot": "svec-sc-cards",
        "org.gnome.Aisleriot": "svec-sc-cards",

        # prohlížeče a komunikace
        "firefox": "svec-sc-brand-firefox",
        "firefox-esr": "svec-sc-brand-firefox",
        "org.mozilla.firefox": "svec-sc-brand-firefox",
        "org.mozilla.Firefox": "svec-sc-brand-firefox",
        "librewolf": "svec-sc-brand-firefox",
        "io.gitlab.librewolf-community": "svec-sc-brand-firefox",
        "floorp": "svec-sc-brand-firefox",
        "waterfox": "svec-sc-brand-firefox",
        "chromium": "svec-sc-brand-chrome",
        "chromium-browser": "svec-sc-brand-chrome",
        "org.chromium.Chromium": "svec-sc-brand-chrome",
        "google-chrome": "svec-sc-brand-chrome",
        "google-chrome-stable": "svec-sc-brand-chrome",
        "com.google.Chrome": "svec-sc-brand-chrome",
        "brave-browser": "svec-web",
        "com.brave.Browser": "svec-web",
        "microsoft-edge": "svec-web",
        "com.microsoft.Edge": "svec-web",
        "opera": "svec-web",
        "vivaldi": "svec-web",
        "tor-browser": "svec-web",
        "thunderbird": "svec-mail",
        "org.mozilla.thunderbird": "svec-mail",
        "eu.betterbird.Betterbird": "svec-mail",
        "betterbird": "svec-mail",
        "geary": "svec-mail",
        "mailspring": "svec-mail",
        "claws-mail": "svec-mail",
        "discord": "svec-sc-brand-discord",
        "com.discordapp.Discord": "svec-sc-brand-discord",
        "vesktop": "svec-sc-brand-discord",
        "webcord": "svec-sc-brand-discord",
        "telegram": "svec-sc-brand-telegram",
        "telegram-desktop": "svec-sc-brand-telegram",
        "org.telegram.desktop": "svec-sc-brand-telegram",
        "signal": "svec-sc-message-2",
        "org.signal.Signal": "svec-sc-message-2",
        "element": "svec-sc-messages",
        "im.riot.Riot": "svec-sc-messages",
        "slack": "svec-sc-brand-slack",
        "com.slack.Slack": "svec-sc-brand-slack",
        "hexchat": "svec-sc-messages",
        "pidgin": "svec-sc-messages",
        "weechat": "svec-sc-messages",
        "zoom": "svec-sc-video",
        "us.zoom.Zoom": "svec-sc-video",
        "org.jitsi.jitsi-meet": "svec-sc-video",
        "skype": "svec-sc-phone-call",
        # kancelář
        "libreoffice-writer": "svec-writer",
        "libreoffice-calc": "svec-tabulky",
        "libreoffice-impress": "svec-prezentace",
        "libreoffice-draw": "svec-sc-vector-bezier",
        "libreoffice-base": "svec-sc-database",
        "libreoffice-math": "svec-sc-math-function",
        "libreoffice-startcenter": "svec-docs",
        "calligrawords": "svec-writer",
        "calligrasheets": "svec-tabulky",
        "calligrastage": "svec-prezentace",
        "calligraflow": "svec-schema",
        "calligrakarbon": "svec-sc-vector-bezier",
        "onlyoffice-desktopeditors": "svec-docs",
        # vývoj
        "code": "svec-sc-brand-vscode",
        "visual-studio-code": "svec-sc-brand-vscode",
        "com.visualstudio.code": "svec-sc-brand-vscode",
        "vscode": "svec-sc-brand-vscode",
        "code-oss": "svec-sc-brand-vscode",
        "vscodium": "svec-sc-brand-vscode",
        "com.vscodium.codium": "svec-sc-brand-vscode",
        "qtcreator": "svec-code",
        "io.qt.QtCreator": "svec-code",
        "qt-creator": "svec-code",
        "eclipse": "svec-code",
        "idea": "svec-code",
        "com.jetbrains.IntelliJ-IDEA": "svec-code",
        "intellij": "svec-code",
        "pycharm": "svec-code",
        "com.jetbrains.PyCharm": "svec-code",
        "webstorm": "svec-code",
        "clion": "svec-code",
        "goland": "svec-code",
        "rider": "svec-code",
        "phpstorm": "svec-code",
        "datagrip": "svec-code",
        "android-studio": "svec-code",
        "com.google.AndroidStudio": "svec-code",
        "vim": "svec-code",
        "gvim": "svec-code",
        "nvim": "svec-code",
        "neovim": "svec-code",
        "neovim-qt": "svec-code",
        "emacs": "svec-code",
        "org.gnu.emacs": "svec-code",
        "sublime-text": "svec-code",
        "sublime_text": "svec-code",
        "com.sublimetext.three": "svec-code",
        "atom": "svec-code",
        "lapce": "svec-code",
        "zed": "svec-zed",
        "dev.zed.Zed": "svec-zed",
        "zed-editor": "svec-zed",
        "org.zed.Zed": "svec-zed",
        "godot": "svec-godot",
        "godot-engine": "svec-godot",
        "godot4": "svec-godot",
        "org.godotengine.Godot": "svec-godot",
        "unityhub": "svec-three",
        "com.unity3d.UnityHub": "svec-three",
        "dbeaver": "svec-sc-database",
        "io.dbeaver.DBeaver": "svec-sc-database",
        "pgadmin4": "svec-sc-database",
        "mysql-workbench": "svec-sc-database",
        "beekeeper-studio": "svec-sc-database",
        "postman": "svec-sc-world",
        "com.getpostman.Postman": "svec-sc-world",
        "insomnia": "svec-sc-world",
        "rest.insomnia.Insomnia": "svec-sc-world",
        "bruno": "svec-sc-world",
        "wireshark": "svec-sc-antenna",
        "org.wireshark.Wireshark": "svec-sc-antenna",
        "nmap": "svec-sc-antenna",
        "zenmap": "svec-sc-antenna",
        "filezilla": "svec-ftp",
        "ghidra": "svec-sc-binary",
        "cutter": "svec-sc-binary",
        "radare2": "svec-sc-binary",
        "gitg": "svec-sc-git-branch",
        "org.gnome.gitg": "svec-sc-git-branch",
        "gitkraken": "svec-sc-git-branch",
        "com.axosoft.GitKraken": "svec-sc-git-branch",
        "github-desktop": "svec-sc-git-branch",
        "git-cola": "svec-sc-git-branch",
        "sublime-merge": "svec-sc-git-branch",
        "kdiff3": "svec-sc-git-branch",
        "designer": "svec-design",
        "linguist": "svec-sc-translate",
        "assistant": "svec-sc-help",
        "glade": "svec-design",
        "qt5ct": "svec-design",
        "qt6ct": "svec-design",
        "kvantum-manager": "svec-design",
        "lxappearance": "svec-design",
        "nwg-look": "svec-design",
        "alacarte": "svec-tools",
        "menulibre": "svec-tools",
        # grafika a 3D
        "gimp": "svec-sc-brush",
        "org.gimp.GIMP": "svec-sc-brush",
        "mypaint": "svec-sc-brush",
        "inkscape": "svec-sc-vector-bezier",
        "org.inkscape.Inkscape": "svec-sc-vector-bezier",
        "pinta": "svec-sc-palette",
        "com.github.PintaProject.Pinta": "svec-sc-palette",
        "darktable": "svec-sc-aperture",
        "org.darktable.Darktable": "svec-sc-aperture",
        "rawtherapee": "svec-sc-aperture",
        "flameshot": "svec-sc-flame",
        "org.flameshot.Flameshot": "svec-sc-flame",
        "gthumb": "svec-sc-photo",
        "org.gnome.gThumb": "svec-sc-photo",
        "blender": "svec-three",
        "org.blender.Blender": "svec-three",
        "freecad": "svec-cad",
        "org.freecad.FreeCAD": "svec-cad",
        "openscad": "svec-cad",
        "org.openscad.OpenSCAD": "svec-cad",
        "kicad": "svec-schema",
        "librecad": "svec-cad",
        "qcad": "svec-cad",
        "solvespace": "svec-cad",
        "geogebra": "svec-sc-math-function",
        "org.geogebra.GeoGebra": "svec-sc-math-function",
        "wxmaxima": "svec-sc-math-function",
        "octave": "svec-sc-chart-line",
        "gnuplot": "svec-sc-chart-line",
        "scilab": "svec-sc-chart-line",
        "rstudio": "svec-sc-chart-line",
        "stellarium": "svec-sc-telescope",
        "org.stellarium.Stellarium": "svec-sc-telescope",
        "celestia": "svec-sc-telescope",
        "avogadro": "svec-sc-atom",
        "gtranslator": "svec-sc-translate",
        "poedit": "svec-sc-translate",
        "dialect": "svec-sc-translate",
        "com.github.gi_lom.dialect": "svec-sc-translate",
        "scribus": "svec-sc-pencil",
        "kile": "svec-sc-file-text",
        "texstudio": "svec-sc-file-text",
        "obsidian": "svec-sc-notebook",
        "md.obsidian.Obsidian": "svec-sc-notebook",
        "joplin": "svec-sc-notebook",
        "org.joplinapp.Joplin": "svec-sc-notebook",
        "logseq": "svec-sc-notebook",
        "zettlr": "svec-sc-notebook",
        "marktext": "svec-markdown",
        "retext": "svec-markdown",
        "marker": "svec-markdown",
        "apostrophe": "svec-markdown",
        # média a hry
        "vlc": "svec-sc-cone",
        "org.videolan.VLC": "svec-sc-cone",
        "mpv": "svec-sc-movie",
        "io.mpv.Mpv": "svec-sc-movie",
        "celluloid": "svec-sc-movie",
        "smplayer": "svec-sc-movie",
        "kaffeine": "svec-sc-movie",
        "audacity": "svec-sc-waveform",
        "org.audacityteam.Audacity": "svec-sc-waveform",
        "ardour": "svec-sc-waveform",
        "lmms": "svec-music",
        "amarok": "svec-music",
        "strawberry": "svec-music",
        "org.strawberrymusicplayer.strawberry": "svec-music",
        "audacious": "svec-music",
        "clementine": "svec-music",
        "deadbeef": "svec-music",
        "spotify": "svec-sc-brand-spotify",
        "com.spotify.Client": "svec-sc-brand-spotify",
        "gpodder": "svec-sc-rss",
        "pavucontrol": "svec-sc-volume",
        "easyeffects": "svec-sc-waveform",
        "com.github.wwmm.easyeffects": "svec-sc-waveform",
        "soundconverter": "svec-sc-waveform",
        "puddletag": "svec-sc-tag",
        "easytag": "svec-sc-tag",
        "picard": "svec-sc-tag",
        "org.musicbrainz.Picard": "svec-sc-tag",
        "openshot": "svec-sc-clapperboard",
        "pitivi": "svec-sc-clapperboard",
        "shotcut": "svec-sc-clapperboard",
        "flowblade": "svec-sc-clapperboard",
        "handbrake": "svec-sc-video",
        "fr.handbrake.ghb": "svec-sc-video",
        "obs": "svec-sc-video",
        "com.obsproject.Studio": "svec-sc-video",
        "simplescreenrecorder": "svec-sc-video",
        "vokoscreenNG": "svec-sc-video",
        "steam": "svec-sc-brand-steam",
        "com.valvesoftware.Steam": "svec-sc-brand-steam",
        "lutris": "svec-sc-device-gamepad-2",
        "net.lutris.Lutris": "svec-sc-device-gamepad-2",
        "heroic": "svec-sc-rocket",
        "com.heroicgameslauncher.hgl": "svec-sc-rocket",
        "bottles": "svec-sc-wine",
        "com.usebottles.bottles": "svec-sc-wine",
        "wine": "svec-sc-wine",
        "playonlinux": "svec-sc-wine",
        "retroarch": "svec-sc-device-gamepad-2",
        "org.libretro.RetroArch": "svec-sc-device-gamepad-2",
        "dosbox": "svec-dosgame",
        "scummvm": "svec-sc-device-gamepad-2",
        "dolphin-emu": "svec-sc-device-gamepad-2",
        "pcsx2": "svec-sc-device-gamepad-2",
        "rpcs3": "svec-sc-device-gamepad-2",
        "duckstation": "svec-sc-device-gamepad-2",
        "supertuxkart": "svec-sc-device-gamepad-2",
        "0ad": "svec-sc-device-gamepad-2",
        "minecraft": "svec-sc-device-gamepad-2",
        "org.prismlauncher.PrismLauncher": "svec-sc-device-gamepad-2",
        "openmw": "svec-sc-device-gamepad-2",
        # systém a nástroje
        "keepassxc": "svec-sc-safe",
        "org.keepassxc.KeePassXC": "svec-sc-safe",
        "bitwarden": "svec-sc-safe",
        "kgpg": "svec-sc-key",
        "gpg": "svec-sc-key",
        "gnupg": "svec-sc-key",
        "yubico": "svec-sc-key",
        "authenticator": "svec-sc-key",
        "virt-manager": "svec-sc-cpu",
        "org.virt_manager.virt-manager": "svec-sc-cpu",
        "virtualbox": "svec-sc-cpu",
        "org.virtualbox": "svec-sc-cpu",
        "qemu": "svec-sc-cpu",
        "vmware": "svec-sc-cpu",
        "gparted": "svec-sc-device-floppy",
        "hwinfo": "svec-sc-cpu",
        "hardinfo": "svec-sc-cpu",
        "cpu-x": "svec-sc-cpu",
        "gpu-viewer": "svec-sc-cpu",
        "gsmartcontrol": "svec-sc-database",
        "bleachbit": "svec-sc-trash",
        "stacer": "svec-sc-trash",
        "timeshift": "svec-backups",
        "deja-dup": "svec-backups",
        "org.gnome.DejaDup": "svec-backups",
        "backintime": "svec-backups",
        "vorta": "svec-backups",
        "pika-backup": "svec-backups",
        "org.gnome.World.PikaBackup": "svec-backups",
        "org.fedoraproject.MediaWriter": "svec-sc-usb",
        "mediawriter": "svec-sc-usb",
        "etcher": "svec-sc-usb",
        "rpi-imager": "svec-sc-usb",
        "transmission": "svec-sc-download",
        "org.transmissionbt.Transmission": "svec-sc-download",
        "qbittorrent": "svec-sc-download",
        "org.qbittorrent.qBittorrent": "svec-sc-download",
        "deluge": "svec-sc-download",
        "nextcloud": "svec-sc-cloud",
        "com.nextcloud.desktopclient.nextcloud": "svec-sc-cloud",
        "owncloud": "svec-sc-cloud",
        "dropbox": "svec-sc-box",
        "megasync": "svec-sc-cloud",
        "onedrive": "svec-sc-cloud",
        "kdeconnect": "svec-sc-device-mobile",
        "org.kde.kdeconnect": "svec-sc-device-mobile",
        "remmina": "svec-sc-cast",
        "org.remmina.Remmina": "svec-sc-cast",
        "vinagre": "svec-sc-cast",
        "okteta": "svec-sc-binary",
        "org.kde.okteta": "svec-sc-binary",
        "ghex": "svec-sc-binary",
        "hexedit": "svec-sc-binary",
        "bless": "svec-sc-binary",
        "printer-manager": "svec-sc-printer",
        "system-config-printer": "svec-sc-printer",
        "onboard": "svec-sc-keyboard",
        "kvkbd": "svec-sc-keyboard",
        "openboard": "svec-sc-chalkboard",
        "htop": "svec-sc-activity",
        "btop": "svec-sc-activity",
        "mission-center": "svec-sc-activity",
        "heaptrack": "svec-sc-chart-area",
        "massif-visualizer": "svec-sc-chart-area",
        "kregexpeditor": "svec-sc-abc",
        "crow-translate": "svec-sc-translate",
        "org.freedesktop.MalcontentControl": "svec-sc-shield-check",
        "malcontent": "svec-sc-shield-check",
        # --- doplnění: KCM stránky / systémové moduly Plasma ---
        "applications-all-symbolic": "svec-extapp",
        "applications-system-symbolic": "svec-desktop",
        "baloo": "svec-sc-search",
        "firewall-config": "svec-sc-shield-check",
        "get-hot-new-stuff": "svec-sc-cloud-download",
        "input-keyboard-virtual": "svec-sc-keyboard",
        "kde-frameworks": "svec-sc-components",
        "kfind": "svec-sc-search",
        "kfontview": "svec-sc-typography",
        "klipper": "svec-sc-clipboard-list",
        "knetattach": "svec-sc-plug",
        "kontact-import-wizard": "svec-sc-download",
        "krfb": "svec-sc-cast",
        "krunner": "svec-sc-run",
        "ktimer": "svec-sc-timer",
        "ktip": "svec-sc-bulb",
        "lighttable": "svec-code",
        "map-globe": "svec-sc-world",
        "plasma-browser-integration": "svec-web",
        "plasmadiscover": "svec-sc-package",
        "plasma-search": "svec-sc-search",
        "plasmashell": "svec-sc-layout-dashboard",
        "speedometer-symbolic": "svec-sc-activity",
        "office-chart-line-symbolic": "svec-sc-chart-line",
        "view-process-system-symbolic": "svec-sc-activity",
        "mark-location-symbolic": "svec-sc-map-pin",
        "preferences-desktop-activities": "svec-sc-activity",
        "preferences-desktop-animations": "svec-sc-sparkles",
        "preferences-desktop-baloo": "svec-sc-search",
        "preferences-desktop-cursors": "svec-sc-pointer",
        "preferences-desktop-default-applications": "svec-extapp",
        "preferences-desktop-effects": "svec-sc-sparkles",
        "preferences-desktop-emoticons": "svec-sc-mood-smile",
        "preferences-desktop-feedback": "svec-sc-megaphone",
        "preferences-desktop-filetype-association": "svec-sc-file-text",
        "preferences-desktop-font-installer": "svec-sc-typography",
        "preferences-desktop-gaming": "svec-sc-device-gamepad-2",
        "preferences-desktop-keyboard-shortcut": "svec-sc-keyboard",
        "preferences-desktop-notification-bell": "svec-sc-bell",
        "preferences-desktop-plasma-theme": "svec-sc-palette",
        "preferences-desktop-sound": "svec-sc-volume",
        "preferences-desktop-tablet": "svec-sc-device-tablet",
        "preferences-desktop-theme-applications": "svec-design",
        "preferences-desktop-theme-global": "svec-sc-palette",
        "preferences-desktop-theme-windowdecorations": "svec-sc-frame",
        "preferences-desktop-thunderbolt": "svec-sc-bolt",
        "preferences-desktop-touchpad": "svec-sc-pointer",
        "preferences-desktop-touchscreen": "svec-sc-device-tablet",
        "preferences-desktop-user-password": "svec-sc-key",
        "preferences-desktop-virtual": "svec-sc-cpu",
        "preferences-devices-printer": "svec-sc-printer",
        "preferences-online-accounts": "svec-sc-users",
        "preferences-security": "svec-sc-shield-check",
        "preferences-smart-status": "svec-sc-database",
        "preferences-system-bluetooth": "svec-sc-bluetooth",
        "preferences-system-login": "svec-sc-user",
        "preferences-system-network-connection": "svec-sc-cable",
        "preferences-system-network-proxy": "svec-sc-router",
        "preferences-system-network-remote": "svec-sc-cast",
        "preferences-system-power-management": "svec-sc-bolt",
        "preferences-system-session-services": "svec-sc-refresh",
        "preferences-system-splash": "svec-sc-sparkles",
        "preferences-system-tabbox": "svec-sc-layout-kanban",
        "preferences-system-users": "svec-sc-users",
        "preferences-system-windows-actions": "svec-sc-layout-kanban",
        "preferences-web-browser-shortcuts": "svec-web",
        "redshift-status-on": "svec-sc-sunset",
        "system-user-prompt": "svec-sc-user-check",
        "utilities-log-viewer": "svec-sc-list-details",
        "xorg": "svec-desktop",
        "org.fedoraproject.AnacondaInstaller": "svec-sc-download",
        "start-here-kde-plasma": "cz.svec.Studio",
        "plasma-symbolic": "svec-sc-components",
        "muon": "svec-sc-package",
        "packagekit": "svec-sc-package",
        "smb4k": "svec-sc-world",
        "org.kde.smb4k": "svec-sc-world",
        "org.kde.kdeconnect.app": "svec-sc-device-mobile",
        "org.kde.plasma-vault": "svec-sc-safe",
        "plasmavault": "svec-sc-safe",
        "org.kde.kcolorchooser": "svec-sc-color-picker",
        # --- nainstalované aplikace bez systémové ikony ---
        "co.anysphere.cursor": "svec-code",
        "cursor": "svec-code",
        "claude-desktop-unofficial": "svec-claude",
        "claude": "svec-claude",
        "claude-desktop": "svec-claude",
        "com.anthropic.claude": "svec-claude",
        "com.anthropic.Claude": "svec-claude",
        "io.anthropic.claude": "svec-claude",
        "devin-desktop": "svec-agent",
        "docker": "svec-docker",
        "docker-desktop": "svec-docker",
        "com.docker.docker-desktop": "svec-docker",
        "ventoy": "svec-ventoy",
        "ventoy-gui": "svec-ventoy",
        "stm32cubeide": "svec-stm32cubeide",
        "st-stm32cubeide-2.1.1": "svec-stm32cubeide",
        "stm32cubeide_project_importer": "svec-stm32cubeide",
        "com.st.stm32cubeide": "svec-stm32cubeide",
        "cz.svec.LibreWolf": "svec-preview",
        "com.rtosta.zapzap": "svec-sc-brand-whatsapp",
        "com.ultimaker.cura": "svec-three",
        "cura": "svec-three",
        "kitty": "svec-terminal",
        "mullvad-browser": "svec-web",
        "rustdesk": "svec-sc-cast",
        "org.dosbox-staging.dosbox-staging": "svec-dosgame",
        "dosbox-staging": "svec-dosgame",
        "org.shotcut.Shotcut": "svec-sc-clapperboard",
        "gtk3-demo": "svec-sc-components",
        "gtk3-widget-factory": "svec-sc-components",
        "ibus": "svec-sc-keyboard",
        "ibus-setup": "svec-sc-keyboard",
        "ibus-anthy": "svec-sc-language",
        "ibus-setup-hangul": "svec-sc-language",
        "ibus-typing-booster": "svec-sc-keyboard",
        "org.freedesktop.IBus.Chewing.Setup": "svec-sc-keyboard",
        "org.gnome.Tecla": "svec-sc-keyboard",
        "org.kde.kwatchgnupg": "svec-sc-key",
        "nvidia-settings": "svec-settings",
        "occ": "svec-sc-cloud",
        "orca": "svec-sc-accessible",
        "pinentry": "svec-lock",
        "yad": "svec-sc-frame",
        "eeschema": "svec-schema",
        "pcbnew": "svec-sc-cpu",
        "gerbview": "svec-sc-scan-eye",
        "bitmap2component": "svec-sc-vector-bezier",
        "pcbcalculator": "svec-sc-calculator",
        "EEZ Studio": "svec-sc-layout-dashboard",
        "cdemu-client": "svec-sc-disc",
        "gcdemu": "svec-sc-disc",
        "eopauthapp": "svec-sc-credit-card",
        "eopcardman": "svec-sc-id",
        "hotspot": "svec-sc-activity",
        "setroubleshoot_icon": "svec-sc-shield-check",
        "designer-qt6": "svec-design",
        "linguist-qt6": "svec-sc-translate",
        "assistant-qt6": "svec-sc-help",
        # --- Wine (včetně hash-generovaných názvů z .lnk) ---
        "winecfg": "svec-sc-adjustments-horizontal",
        "winefile": "svec-sc-folder",
        "winemine": "svec-sc-flag",
        "winetricks": "svec-sc-wand",
        "winhelp": "svec-sc-help",
        "winhlp32": "svec-sc-help",
        "winebrowser": "svec-sc-wine",
        "regedit": "svec-sc-list-details",
        "notepad": "svec-sc-file-text",
        "wordpad": "svec-writer",
        "msiexec": "svec-sc-wine",
        "wscript": "svec-sc-wine",
        "rundll32": "svec-sc-wine",
        "2905_wscript.0": "svec-sc-wine",
        "5742_rundll32.0": "svec-sc-wine",
        "D23E_msiexec.0": "svec-sc-wine",
        "C06E_winhlp32.0": "svec-sc-help",
        "D15F_hh.0": "svec-sc-help",
        "0637_PresentationHost.0": "svec-sc-wine",
    },
    "places": {
        "folder": "svec-sc-folder",
        "folder-open": "svec-sc-folder-open",
        "inode-directory": "svec-sc-folder",
        "folder-documents": "svec-sc-folder",
        "folder-download": "svec-sc-download",
        "folder-music": "svec-music",
        "folder-pictures": "svec-sc-photo",
        "folder-videos": "svec-sc-movie",
        "folder-video": "svec-sc-movie",
        "folder-image": "svec-sc-photo",
        "folder-publicshare": "svec-sc-users",
        "folder-templates": "svec-sc-stack-2",
        "folder-remote": "svec-sc-world",
        "folder-network": "svec-sc-world",
        "folder-locked": "svec-lock",
        "folder-encrypted": "svec-lock",
        "folder-mail": "svec-mail",
        "folder-recent": "svec-sc-history",
        "folder-activities": "svec-sc-activity",
        "folder-games": "svec-sc-device-gamepad-2",
        "folder-git": "svec-sc-git-branch",
        "folder-development": "svec-code",
        "folder-scripts": "svec-sc-terminal-2",
        "folder-print": "svec-sc-printer",
        "folder-temp": "svec-sc-clock",
        "folder-important": "svec-sc-flag",
        "folder-favorites": "svec-sc-star",
        "folder-txt": "svec-sc-file-text",
        "folder-sound": "svec-music",
        "folder-saved-search": "svec-sc-search",
        "folder-smart": "svec-sc-wand",
        "user-home": "svec-sc-home",
        "user-desktop": "svec-desktop",
        "user-trash": "svec-sc-trash",
        "user-trash-full": "svec-sc-trash",
        "user-identity": "svec-sc-id",
        "network-server": "svec-sc-server",
        "network-server-database": "svec-sc-database",
        "network-workgroup": "svec-sc-world",
        "network-local": "svec-sc-world",
        "network-file-system": "svec-sc-world",
        "start-here": "cz.svec.Studio",
        "start-here-kde": "cz.svec.Studio",
        "start-here-fedora": "cz.svec.Studio",
        "distributor-logo": "cz.svec.Studio",
        "distributor-logo-fedora": "cz.svec.Studio",
        "fedora-logo-icon": "cz.svec.Studio",
        "fedora-logo": "cz.svec.Studio",
        "fedora-logo-small": "cz.svec.Studio",
        "kde": "cz.svec.Studio",
        "plasma": "cz.svec.Studio",
    },
    "actions": {
        "document-new": "svec-sc-file",
        "document-open": "svec-sc-folder-open",
        "document-open-folder": "svec-sc-folder-open",
        "document-open-recent": "svec-sc-history",
        "document-save": "svec-save",
        "document-save-as": "svec-save",
        "document-save-all": "svec-save",
        "document-close": "svec-sc-x",
        "document-revert": "svec-sc-rotate-clockwise",
        "document-print": "svec-sc-printer",
        "document-print-preview": "svec-sc-eye",
        "document-print-frame": "svec-sc-eye",
        "document-properties": "svec-sc-file-text",
        "document-edit": "svec-edit",
        "document-encrypt": "svec-lock",
        "document-decrypt": "svec-sc-lock-open",
        "document-share": "svec-sc-share",
        "document-send": "svec-sc-send",
        "document-import": "svec-sc-download",
        "document-export": "svec-sc-upload",
        "document-sign": "svec-sc-pencil",
        "edit-undo": "svec-sc-refresh",
        "edit-redo": "svec-sc-rotate-clockwise",
        "edit-cut": "svec-sc-scissors",
        "edit-copy": "svec-sc-copy",
        "edit-move": "svec-sc-download",
        "document-move": "svec-sc-download",
        "object-move": "svec-sc-download",
        "link": "svec-sc-link",
        "edit-paste": "svec-sc-clipboard-list",
        "edit-delete": "svec-sc-trash",
        "edit-delete-shred": "svec-sc-trash",
        "edit-clear": "svec-sc-eraser",
        "edit-clear-all": "svec-sc-eraser",
        "edit-clear-list": "svec-sc-eraser",
        "edit-find": "svec-sc-search",
        "edit-find-replace": "svec-sc-search",
        "edit-select-all": "svec-sc-checkbox",
        "edit-select": "svec-sc-checkbox",
        "edit-rename": "svec-edit",
        "edit-link": "svec-sc-link",
        "edit-download": "svec-sc-download",
        "go-home": "svec-sc-home",
        "go-up": "svec-kit-chevron-up",
        "go-down": "svec-kit-chevron-down",
        "go-previous": "svec-kit-chevron-left",
        "go-next": "svec-kit-chevron-right",
        "go-first": "svec-kit-chevron-left",
        "go-last": "svec-kit-chevron-right",
        "go-jump": "svec-sc-external-link",
        "go-top": "svec-kit-chevron-up",
        "go-bottom": "svec-kit-chevron-down",
        "go-parent-folder": "svec-kit-chevron-up",
        "view-refresh": "svec-sc-refresh",
        "view-fullscreen": "svec-sc-maximize",
        "view-restore": "svec-sc-minimize",
        "view-list-icons": "svec-sc-layout-grid",
        "view-list-details": "svec-sc-list-details",
        "view-list-text": "svec-sc-list",
        "view-grid": "svec-sc-layout-grid",
        "view-sort-ascending": "svec-sc-adjustments-horizontal",
        "view-sort-descending": "svec-sc-adjustments-horizontal",
        "view-filter": "svec-sc-filter",
        "view-visible": "svec-sc-eye",
        "view-hidden": "svec-sc-eye-off",
        "view-preview": "svec-preview",
        "view-split-left-right": "svec-split",
        "view-split-top-bottom": "svec-split",
        "view-group": "svec-sc-stack-2",
        "zoom-in": "svec-zoomIn",
        "zoom-out": "svec-zoomOut",
        "zoom-original": "svec-sc-focus-2",
        "zoom-fit-best": "svec-sc-maximize",
        "zoom-fit-width": "svec-sc-maximize",
        "zoom-fit-height": "svec-sc-maximize",
        "list-add": "svec-kit-plus",
        "list-remove": "svec-kit-minus",
        "list-add-user": "svec-sc-user-plus",
        "list-remove-user": "svec-sc-user-cog",
        "list-add-font": "svec-sc-typography",
        "process-stop": "svec-sc-player-stop",
        "dialog-ok": "svec-kit-check",
        "dialog-ok-apply": "svec-kit-check",
        "dialog-apply": "svec-kit-check",
        "dialog-yes": "svec-kit-check",
        "dialog-cancel": "svec-sc-x",
        "dialog-no": "svec-sc-x",
        "dialog-close": "svec-kit-close",
        "dialog-ok-apply-symbolic": "svec-kit-check",
        "window-close": "svec-sc-x",
        "window-minimize": "svec-min",
        "window-maximize": "svec-sc-maximize",
        "window-restore": "svec-sc-minimize",
        "window-duplicate": "svec-sc-copy",
        "window-new": "svec-kit-plus",
        "window-pin": "svec-sc-pinned",
        "window-keep-above": "svec-sc-pinned",
        "system-run": "svec-sc-run",
        "application-exit": "svec-logout",
        "application-quit": "svec-logout",
        "system-shutdown": "svec-power",
        "system-reboot": "svec-sc-refresh",
        "system-restart": "svec-sc-refresh",
        "system-log-out": "svec-logout",
        "system-lock-screen": "svec-lock",
        "system-suspend": "svec-moon",
        "system-hibernate": "svec-sc-snowflake",
        "system-suspend-hibernate": "svec-sc-snowflake",
        "system-switch-user": "svec-sc-users",
        "system-upgrade": "svec-sc-cloud-download",
        "tools-check-spelling": "svec-sc-abc",
        "tools-report-bug": "svec-sc-bug",
        "configure": "svec-settings",
        "settings-configure": "svec-settings",
        "folder-new": "svec-sc-folder-plus",
        "tab-new": "svec-kit-plus",
        "tab-new-background": "svec-kit-plus",
        "tab-close": "svec-sc-x",
        "tab-close-other": "svec-sc-x",
        "tab-detach": "svec-sc-external-link",
        "tab-duplicate": "svec-sc-copy",
        "format-list-unordered": "svec-sc-list",
        "format-list-ordered": "svec-sc-list-details",
        "format-justify-left": "svec-sc-list-details",
        "format-justify-right": "svec-sc-list-details",
        "format-justify-center": "svec-sc-list-details",
        "format-justify-fill": "svec-sc-list-details",
        "format-text-color": "svec-sc-color-picker",
        "format-text-highlight": "svec-sc-highlighter",
        "format-font-size-more": "svec-sc-typography",
        "format-font-size-less": "svec-sc-typography",
        "format-text-direction-ltr": "svec-sc-typography",
        "format-text-direction-rtl": "svec-sc-typography",
        "media-playback-start": "svec-sc-player-play",
        "media-playback-pause": "svec-sc-player-pause",
        "media-playback-stop": "svec-sc-player-stop",
        "media-record": "svec-sc-player-record",
        "media-skip-forward": "svec-sc-player-skip-forward",
        "media-skip-backward": "svec-sc-player-skip-back",
        "media-seek-forward": "svec-sc-player-track-next",
        "media-seek-backward": "svec-sc-player-track-prev",
        "media-eject": "svec-sc-upload",
        "media-playlist-repeat": "svec-sc-repeat",
        "media-playlist-shuffle": "svec-sc-arrows-shuffle",
        "media-playlist-normal": "svec-sc-list",
        "audio-volume-high": "svec-sc-volume",
        "audio-volume-medium": "svec-sc-volume",
        "audio-volume-low": "svec-sc-volume",
        "audio-volume-muted": "svec-sc-volume-off",
        "audio-ready": "svec-sc-volume",
        "microphone-sensitivity-high": "svec-sc-microphone",
        "microphone-sensitivity-medium": "svec-sc-microphone",
        "microphone-sensitivity-low": "svec-sc-microphone",
        "microphone-sensitivity-muted": "svec-sc-microphone-off",
        "mic-on": "svec-sc-microphone",
        "mic-off": "svec-sc-microphone-off",
        "camera-on": "svec-sc-camera",
        "camera-off": "svec-sc-camera-off",
        "object-select": "svec-sc-checkbox",
        "object-locked": "svec-lock",
        "object-unlocked": "svec-sc-lock-open",
        "object-hidden": "svec-sc-eye-off",
        "object-visible": "svec-sc-eye",
        "object-group": "svec-sc-stack-2",
        "object-ungroup": "svec-sc-components",
        "object-order-front": "svec-sc-stack-2",
        "object-order-back": "svec-sc-stack-2",
        "object-order-raise": "svec-sc-stack-2",
        "object-order-lower": "svec-sc-stack-2",
        "bookmark-new": "svec-sc-bookmark",
        "bookmarks": "svec-sc-book",
        "bookmark-remove": "svec-kit-minus",
        "bookmarks-organize": "svec-sc-book",
        "download": "svec-sc-download",
        "download-later": "svec-sc-clock",
        "upload": "svec-sc-upload",
        "mail-message-new": "svec-sc-pencil-plus",
        "mail-send": "svec-sc-send",
        "mail-reply-sender": "svec-sc-mail",
        "mail-reply-all": "svec-sc-mail-opened",
        "mail-forward": "svec-sc-mail-forward",
        "mail-receive": "svec-sc-inbox",
        "mail-mark-read": "svec-sc-mail-opened",
        "mail-mark-unread": "svec-sc-mail",
        "mail-mark-important": "svec-sc-flag",
        "mail-flag": "svec-sc-flag",
        "mail-delete": "svec-sc-trash",
        "mail-folder-inbox": "svec-sc-inbox",
        "mail-folder-outbox": "svec-sc-send",
        "mail-folder-sent": "svec-sc-send",
        "mail-folder-trash": "svec-sc-trash",
        "insert-image": "svec-sc-photo",
        "insert-link": "svec-sc-link",
        "insert-text": "svec-sc-typography",
        "insert-table": "svec-tabulky",
        "insert-horizontal-rule": "svec-kit-minus",
        "insert-math-expression": "svec-sc-math-function",
        "insert-page-break": "svec-sc-file",
        "transform-crop": "svec-sc-crop",
        "transform-scale": "svec-sc-maximize",
        "transform-rotate": "svec-sc-rotate-clockwise",
        "transform-move": "svec-sc-frame",
        "transform-shear-left": "svec-sc-triangle",
        "transform-shear-right": "svec-sc-triangle",
        "transform-flip-horizontal": "svec-sc-arrows-shuffle",
        "transform-flip-vertical": "svec-sc-arrows-shuffle",
        "draw-brush": "svec-sc-brush",
        "draw-eraser": "svec-sc-eraser",
        "draw-freehand": "svec-sc-pencil",
        "draw-pencil": "svec-sc-pencil",
        "draw-text": "svec-sc-typography",
        "draw-rectangle": "svec-sc-square",
        "draw-ellipse": "svec-sc-circle",
        "draw-circle": "svec-sc-circle",
        "draw-polygon": "svec-sc-hexagon",
        "draw-line": "svec-kit-minus",
        "draw-star": "svec-sc-star",
        "draw-calligraphy": "svec-sc-brush",
        "draw-donut": "svec-sc-circle",
        "draw-highlight": "svec-sc-highlighter",
        "draw-spiral": "svec-sc-wave-sine",
        "draw-bezier-curves": "svec-sc-vector-bezier",
        "draw-path": "svec-sc-vector-bezier",
        "object-stroke": "svec-sc-pencil",
        "object-fill": "svec-sc-bucket",
        "object-rotate-left": "svec-sc-refresh",
        "object-rotate-right": "svec-sc-rotate-clockwise",
        "object-flip-horizontal": "svec-sc-arrows-shuffle",
        "object-flip-vertical": "svec-sc-arrows-shuffle",
        "color-gradient": "svec-sc-palette",
        "color-picker": "svec-sc-color-picker",
        "fill-color": "svec-sc-bucket",
        "stroke-color": "svec-sc-pencil",
        "align-horizontal-left": "svec-sc-list-details",
        "align-horizontal-center": "svec-sc-list-details",
        "align-horizontal-right": "svec-sc-list-details",
        "align-vertical-top": "svec-sc-list-details",
        "align-vertical-center": "svec-sc-list-details",
        "align-vertical-bottom": "svec-sc-list-details",
        "align-horizontal-distribute": "svec-sc-list-details",
        "align-vertical-distribute": "svec-sc-list-details",
        "changes-allow": "svec-kit-check",
        "changes-prevent": "svec-sc-x",
        "contact-new": "svec-sc-user-plus",
        "appointment-new": "svec-sc-calendar-event",
        "face-smile": "svec-sc-mood-smile",
        "flag": "svec-sc-flag",
        "rating": "svec-sc-star",
        "rating-unrated": "svec-sc-star",
        "favorite": "svec-sc-heart",
        "games-config-tiles": "svec-sc-layout-grid",
        "games-config-options": "svec-settings",
        "games-config-custom": "svec-settings",
        "games-config-theme": "svec-sc-palette",
        "games-difficult": "svec-sc-dice",
        "games-highscores": "svec-sc-trophy",
        "games-solve": "svec-sc-wand",
        "games-hint": "svec-sc-bulb",
        "tools-media-optical-burn": "svec-sc-disc",
        "tools-rip-audio-cd": "svec-sc-disc",
        "tools-rip-optical-cd": "svec-sc-disc",
        "tools-rip-video-dvd": "svec-sc-disc",
        "player-time": "svec-sc-timer",
        "player-volume": "svec-sc-volume",
        "playlist-generator": "svec-sc-playlist",
        "tag": "svec-sc-tag",
        "run-build": "svec-sc-run",
        "run-build-configure": "svec-settings",
        "run-build-clean": "svec-sc-eraser",
        "run-build-install": "svec-sc-download",
        "run-build-prune": "svec-sc-trash",
        "run-build-install-root": "svec-sc-download",
        "run-build-file": "svec-sc-run",
        "run": "svec-sc-run",
        "quickopen": "svec-sc-search",
        "quickopen-function": "svec-sc-search",
        "quickopen-file": "svec-sc-file",
        "quickopen-line": "svec-sc-search",
        "quickopen-class": "svec-sc-search",
        "code-class": "svec-code",
        "code-context": "svec-code",
        "code-function": "svec-code",
        "code-variable": "svec-code",
        "code-block": "svec-code",
        "debug-run": "svec-sc-bug",
        "debug-step-over": "svec-sc-player-track-next",
        "debug-step-into": "svec-sc-player-track-next",
        "debug-step-out": "svec-sc-player-track-prev",
        "debug-execute-to-cursor": "svec-sc-player-play",
        "debug-run-cursor": "svec-sc-player-play",
        "debug-restart": "svec-sc-refresh",
        "debug-interrupt": "svec-sc-player-pause",
        "debug-toggle-breakpoint": "svec-sc-circle",
        "debug-remove-breakpoint": "svec-sc-x",
        "project-development-open": "svec-sc-folder-open",
        "project-open": "svec-sc-folder-open",
        "project-development-close": "svec-sc-x",
        "project-development-new-template": "svec-sc-components",
        "document-encrypted": "svec-lock",
        "document-decrypted": "svec-sc-lock-open",
        "filename-space-amarok": "svec-sc-file",
        "filename-divider": "svec-kit-minus",
        "filename-and-amarok": "svec-sc-file-text",
        "filename-or-amarok": "svec-sc-file-text",
        "filename-tracks-amarok": "svec-sc-list",
        "filename-year-amarok": "svec-sc-calendar",
        "filename-dash-amarok": "svec-kit-minus",
        "filename-underscore-amarok": "svec-kit-minus",
        "filename-bpm-amarok": "svec-sc-heartbeat",
        "filename-sample-rate": "svec-sc-waveform",
        "filename-filetype-amarok": "svec-sc-file-text",
        "filename-comment-amarok": "svec-sc-message-2",
        "filename-composer-amarok": "svec-sc-user",
        "filename-disc-number-amarok": "svec-sc-disc",
        "filename-group-length": "svec-sc-list-details",
        "filename-group-tracks": "svec-sc-list",
        "filename-ignore-amarok": "svec-sc-eye-off",
        "filename-last-played": "svec-sc-history",
        "filename-moodbar": "svec-sc-mood-smile",
        "filename-title-amarok": "svec-sc-file-text",
        "filename-track-amarok": "svec-sc-music",
        "filename-playcount-amarok": "svec-sc-chart-bar",
        "filename-extension": "svec-sc-file",
        "filename-folder-amarok": "svec-sc-folder",
        "filename-album-amarok": "svec-sc-album",
        "filename-artist-amarok": "svec-sc-user",
        "filename-genre-amarok": "svec-sc-tag",
        "filename-rating-amarok": "svec-sc-star",
        "filename-score-amarok": "svec-sc-percentage",
        "filename-bitrate-amarok": "svec-sc-waveform",
        "filename-label-amarok": "svec-sc-tag",
        "filename-cover-amarok": "svec-sc-photo",
    },
    "mimetypes": {
        "text-x-generic": "svec-sc-file-text",
        "text-plain": "svec-sc-file-text",
        "text-x-preview": "svec-sc-eye",
        "text-html": "svec-sc-code",
        "application-xhtml+xml": "svec-sc-code",
        "text-xml": "svec-sc-xml",
        "application-xml": "svec-sc-xml",
        "application-json": "svec-sc-braces",
        "application-ld+json": "svec-sc-braces",
        "application-x-yaml": "svec-sc-list-details",
        "text-yaml": "svec-sc-list-details",
        "text-x-markdown": "svec-markdown",
        "text-markdown": "svec-markdown",
        "application-pdf": "svec-docs",
        "application-rtf": "svec-odt",
        "text-enriched": "svec-odt",
        "application-x-abiword": "svec-odt",
        "application-msword": "svec-odt",
        "application-vnd.openxmlformats-officedocument.wordprocessingml.document": "svec-odt",
        "application-vnd.oasis.opendocument.text": "svec-odt",
        "application-vnd.sun.xml.writer": "svec-odt",
        "x-office-document": "svec-odt",
        "application-vnd.ms-excel": "svec-tabulky",
        "application-vnd.openxmlformats-officedocument.spreadsheetml.sheet": "svec-tabulky",
        "application-vnd.oasis.opendocument.spreadsheet": "svec-tabulky",
        "x-office-spreadsheet": "svec-tabulky",
        "text-csv": "svec-tabulky",
        "application-vnd.ms-powerpoint": "svec-prezentace",
        "application-vnd.openxmlformats-officedocument.presentationml.presentation": "svec-prezentace",
        "application-vnd.oasis.opendocument.presentation": "svec-prezentace",
        "x-office-presentation": "svec-prezentace",
        "application-vnd.oasis.opendocument.graphics": "svec-sc-vector-bezier",
        "x-office-drawing": "svec-sc-vector-bezier",
        "application-vnd.oasis.opendocument.formula": "svec-sc-math-function",
        "x-office-formula": "svec-sc-math-function",
        "application-vnd.oasis.opendocument.database": "svec-sc-database",
        "x-office-database": "svec-sc-database",
        "x-office-calendar": "svec-calendar",
        "text-calendar": "svec-calendar",
        "text-vcalendar": "svec-calendar",
        "x-office-address-book": "svec-sc-address-book",
        "text-vcard": "svec-sc-address-book",
        "text-directory": "svec-sc-address-book",
        "image-x-generic": "svec-sc-photo",
        "image-png": "svec-sc-photo",
        "image-jpeg": "svec-sc-photo",
        "image-gif": "svec-sc-photo",
        "image-bmp": "svec-sc-photo",
        "image-webp": "svec-sc-photo",
        "image-tiff": "svec-sc-photo",
        "image-x-psd": "svec-sc-photo",
        "image-x-xcf": "svec-sc-photo",
        "image-x-krita": "svec-sc-brush",
        "image-svg+xml": "svec-sc-vector-bezier",
        "audio-x-generic": "svec-sc-music",
        "audio-mpeg": "svec-sc-music",
        "audio-flac": "svec-sc-music",
        "audio-ogg": "svec-sc-music",
        "audio-wav": "svec-sc-music",
        "audio-x-wav": "svec-sc-music",
        "audio-aac": "svec-sc-music",
        "audio-x-playlist": "svec-sc-playlist",
        "application-x-m3u": "svec-sc-playlist",
        "audio-x-mpegurl": "svec-sc-playlist",
        "audio-x-scpls": "svec-sc-playlist",
        "video-x-generic": "svec-sc-movie",
        "video-mp4": "svec-sc-movie",
        "video-x-matroska": "svec-sc-movie",
        "video-webm": "svec-sc-movie",
        "video-x-msvideo": "svec-sc-movie",
        "video-mpeg": "svec-sc-movie",
        "video-quicktime": "svec-sc-movie",
        "application-octet-stream": "svec-sc-file",
        "unknown": "svec-sc-file",
        "application-x-unknown": "svec-sc-file",
        "application-x-msi": "svec-extapp",
        "application-x-appimage": "svec-extapp",
        "application-zip": "svec-archiv",
        "application-x-archive": "svec-archiv",
        "application-x-tar": "svec-archiv",
        "application-gzip": "svec-archiv",
        "application-x-bzip": "svec-archiv",
        "application-x-bzip-compressed-tar": "svec-archiv",
        "application-x-compressed-tar": "svec-archiv",
        "application-x-7z-compressed": "svec-archiv",
        "application-x-rar": "svec-archiv",
        "application-vnd.rar": "svec-archiv",
        "application-x-xz": "svec-archiv",
        "application-x-lzma": "svec-archiv",
        "application-x-gtar": "svec-archiv",
        "application-x-zstd-compressed-tar": "svec-archiv",
        "package-x-generic": "svec-sc-package",
        "application-vnd.debian.binary-package": "svec-sc-package",
        "application-x-deb": "svec-sc-package",
        "application-x-rpm": "svec-sc-package",
        "application-vnd.flatpak": "svec-sc-package",
        "application-x-flatpak": "svec-sc-package",
        "application-x-flatpak-bundle": "svec-sc-package",
        "application-x-snap": "svec-sc-package",
        "application-x-iso": "svec-sc-disc",
        "application-x-cd-image": "svec-sc-disc",
        "application-x-raw-disk-image": "svec-sc-disc",
        "application-x-shellscript": "svec-sc-terminal-2",
        "text-x-script": "svec-sc-terminal-2",
        "application-x-python": "svec-sc-code",
        "text-x-python": "svec-sc-code",
        "application-x-perl": "svec-sc-code",
        "text-x-csrc": "svec-sc-code",
        "text-x-c++src": "svec-sc-code",
        "text-x-chdr": "svec-sc-code",
        "text-x-c++hdr": "svec-sc-code",
        "text-x-java": "svec-sc-coffee",
        "application-x-java-archive": "svec-sc-coffee",
        "text-x-javascript": "svec-sc-code",
        "application-javascript": "svec-sc-code",
        "text-x-typescript": "svec-sc-code",
        "text-x-php": "svec-sc-code",
        "application-x-php": "svec-sc-code",
        "text-x-ruby": "svec-sc-code",
        "text-x-csharp": "svec-sc-code",
        "text-x-go": "svec-sc-code",
        "text-x-rust": "svec-rust",
        "text-x-rustsrc": "svec-rust",
        "text-x-patch": "svec-sc-git-branch",
        "text-x-diff": "svec-sc-git-branch",
        "text-x-sql": "svec-sc-database",
        "application-sql": "svec-sc-database",
        "application-vnd.sqlite3": "svec-sc-database",
        "application-x-sqlite3": "svec-sc-database",
        "font-x-generic": "svec-sc-typography",
        "application-font-woff": "svec-sc-typography",
        "application-x-font-ttf": "svec-sc-typography",
        "application-x-font-otf": "svec-sc-typography",
        "font-ttf": "svec-sc-typography",
        "font-otf": "svec-sc-typography",
        "model": "svec-three",
        "model-obj": "svec-three",
        "model-stl": "svec-three",
        "application-x-blender": "svec-three",
        "application-epub+zip": "svec-sc-book",
        "application-x-mobi8-ebook": "svec-sc-book",
        "application-x-cbr": "svec-sc-book",
        "application-x-cbt": "svec-sc-book",
        "application-x-cbz": "svec-sc-book",
        "application-x-bittorrent": "svec-sc-download",
        "x-scheme-handler/magnet": "svec-sc-magnet",
        "x-scheme-handler/http": "svec-web",
        "x-scheme-handler/https": "svec-web",
        "x-scheme-handler/mailto": "svec-mail",
        "x-scheme-handler/ftp": "svec-ftp",
        "x-scheme-handler/tel": "svec-sc-phone-call",
        "message-rfc822": "svec-mail",
        "application-mbox": "svec-mail",
        "application-pgp-keys": "svec-sc-key",
        "application-pgp-signature": "svec-sc-fingerprint",
        "application-pgp-encrypted": "svec-lock",
        "application-pkcs12": "svec-sc-certificate",
        "application-x-x509-ca-cert": "svec-sc-certificate",
        "application-pkix-cert": "svec-sc-certificate",
        "text-x-gettext-translation": "svec-sc-translate",
        "application-gpx+xml": "svec-sc-map-pin",
        "application-geo+json": "svec-maps",
        "application-x-subrip": "svec-sc-messages",
        "text-x-ssa": "svec-sc-messages",
        "application-vnd.iccprofile": "svec-sc-color-picker",
        "media-optical-audio": "svec-sc-disc",
    },
    "devices": {
        "computer": "svec-sc-device-desktop",
        "computer-laptop": "svec-sc-device-laptop",
        "video-display": "svec-sc-device-desktop",
        "display": "svec-sc-device-desktop",
        "display-projector": "svec-sc-presentation",
        "video-projector": "svec-sc-presentation",
        "drive-harddisk": "svec-sc-database",
        "drive-harddisk-usb": "svec-sc-usb",
        "drive-removable-media": "svec-sc-usb",
        "drive-removable-media-usb": "svec-sc-usb",
        "media-removable": "svec-sc-usb",
        "media-flash": "svec-sc-usb",
        "media-floppy": "svec-sc-device-floppy",
        "media-optical": "svec-sc-disc",
        "media-optical-cd": "svec-sc-disc",
        "media-optical-dvd": "svec-sc-disc",
        "media-optical-bd": "svec-sc-disc",
        "media-tape": "svec-sc-device-floppy",
        "audio-card": "svec-sc-volume",
        "audio-headphones": "svec-sc-headphones",
        "audio-headset": "svec-sc-headphones",
        "audio-input-microphone": "svec-sc-microphone",
        "audio-speakers": "svec-sc-speakerphone",
        "camera-photo": "svec-sc-camera",
        "camera-web": "svec-sc-camera",
        "phone": "svec-sc-device-mobile",
        "smartphone": "svec-sc-device-mobile",
        "tablet": "svec-sc-device-tablet",
        "pda": "svec-sc-device-mobile",
        "input-keyboard": "svec-sc-keyboard",
        "input-mouse": "svec-sc-pointer",
        "input-tablet": "svec-sc-device-tablet",
        "input-touchpad": "svec-sc-pointer",
        "input-gaming": "svec-sc-device-gamepad-2",
        "input-dialpad": "svec-sc-keyboard",
        "printer": "svec-sc-printer",
        "printer-network": "svec-sc-printer",
        "scanner": "svec-sc-scan-eye",
        "cpu": "svec-sc-cpu",
        "gpu": "svec-sc-cpu",
        "ram": "svec-sc-cpu",
        "memory": "svec-sc-cpu",
        "network-card": "svec-sc-wifi",
        "network-modem": "svec-sc-router",
        "modem": "svec-sc-router",
        "network-router": "svec-sc-router",
        "uninterruptible-power-supply": "svec-sc-bolt",
        "disk-quota": "svec-sc-database",
        "multimedia-player": "svec-sc-device-tv",
        "video-television": "svec-sc-device-tv",
        "tv": "svec-sc-device-tv",
        "ac-adapter": "svec-sc-plug",
        "drive-optical": "svec-sc-disc",
        "webcam": "svec-sc-camera",
        "media-dac": "svec-sc-headphones",
    },
    "status": {
        "dialog-error": "svec-sc-alert-circle",
        "dialog-warning": "svec-sc-alert-triangle",
        "dialog-information": "svec-sc-info-circle",
        "dialog-question": "svec-sc-help",
        "dialog-password": "svec-lock",
        "security-high": "svec-sc-shield-check",
        "security-medium": "svec-sc-shield-check",
        "security-low": "svec-sc-shield-off",
        "user-available": "svec-sc-user-check",
        "user-away": "svec-sc-moon",
        "user-busy": "svec-sc-minus",
        "user-offline": "svec-sc-user",
        "user-invisible": "svec-sc-eye-off",
        "user-idle": "svec-sc-hourglass",
        "network-wired": "svec-sc-cable",
        "network-wireless": "svec-sc-wifi",
        "network-wireless-signal-excellent": "svec-sc-wifi",
        "network-wireless-signal-good": "svec-sc-wifi",
        "network-wireless-signal-ok": "svec-sc-wifi",
        "network-wireless-signal-weak": "svec-sc-wifi",
        "network-wireless-signal-none": "svec-sc-wifi-off",
        "network-offline": "svec-sc-wifi-off",
        "network-error": "svec-sc-alert-triangle",
        "network-connect": "svec-sc-plug",
        "network-disconnect": "svec-sc-plug",
        "network-vpn": "svec-sc-shield-check",
        "network-mobile": "svec-sc-antenna",
        "network-bluetooth": "svec-sc-bluetooth",
        "bluetooth": "svec-sc-bluetooth",
        "bluetooth-active": "svec-sc-bluetooth",
        "bluetooth-disabled": "svec-sc-bluetooth",
        "task-complete": "svec-kit-check",
        "task-ongoing": "svec-sc-activity",
        "task-past-due": "svec-sc-alarm",
        "task-recurring": "svec-sc-repeat",
        "task-attempt": "svec-sc-target",
        "task-delegate": "svec-sc-handshake",
        "task-rejected": "svec-sc-x",
        "task-accepted": "svec-kit-check",
        "task-attention": "svec-sc-alert-circle",
        "image-missing": "svec-sc-photo-off",
        "image-loading": "svec-sc-photo",
        "call-start": "svec-sc-phone-call",
        "call-stop": "svec-sc-phone-off",
        "call-incoming": "svec-sc-phone-call",
        "call-outgoing": "svec-sc-phone-call",
        "call-missed": "svec-sc-phone-off",
        "mail-unread": "svec-sc-mail",
        "mail-read": "svec-sc-mail-opened",
        "mail-tagged": "svec-sc-tag",
        "mail-attachment": "svec-sc-paperclip",
        "mail-replied": "svec-sc-mail-forward",
        "mail-signed": "svec-sc-certificate",
        "mail-signed-full": "svec-sc-certificate",
        "mail-encrypted": "svec-lock",
        "mail-encrypted-full": "svec-lock",
        "weather-clear": "svec-sc-sun",
        "weather-clear-night": "svec-moon",
        "weather-few-clouds": "svec-sc-cloud",
        "weather-few-clouds-night": "svec-sc-cloud",
        "weather-overcast": "svec-sc-cloud",
        "weather-showers": "svec-sc-cloud-rain",
        "weather-showers-scattered": "svec-sc-cloud-rain",
        "weather-storm": "svec-sc-cloud-storm",
        "weather-snow": "svec-sc-cloud-snow",
        "weather-fog": "svec-sc-cloud",
        "weather-windy": "svec-sc-wind",
        "weather-hail": "svec-sc-cloud-snow",
        "weather-freezing-rain": "svec-sc-cloud-rain",
        "weather-severe-alert": "svec-sc-tornado",
        "notification-active": "svec-sc-bell",
        "notification-disabled": "svec-sc-bell-off",
        "notification-inactive": "svec-sc-bell",
        "notifications": "svec-sc-bell",
        "preferences-desktop-notification": "svec-sc-bell",
        "preferences-system-tray": "svec-sc-layout-grid",
        "org.kde.plasma.systemtray": "svec-sc-layout-grid",
        "mediacontroller": "svec-sc-player-play",
        "plasma-mediacontroller": "svec-sc-player-play",
        "mediaplayer": "svec-sc-player-play",
        "plasma-browser-integration": "svec-sc-player-play",
        "weather-none": "svec-sc-cloud",
        "weather-none-available": "svec-sc-cloud",
        "power-profile-power-saver": "svec-sc-leaf",
        "power-profile-balanced": "svec-sc-scale",
        "power-profile-performance": "svec-sc-bolt",
        "powerdevil": "svec-sc-bolt",
        "plasmavault-symbolic": "svec-sc-safe",
        "kdeconnect-indicator": "svec-sc-device-mobile",
        "nightcolor": "svec-sc-moon-stars",
        "nightcoloractive": "svec-sc-sunset",
        "ksysguardd": "svec-sc-activity",
        "osd-duplicate": "svec-sc-copy",
        "osd-sbs-left": "svec-sc-layout-grid",
        "osd-sbs-right": "svec-sc-layout-grid",
        "osd-shutd-screen": "svec-sc-device-desktop",
        "osd-shutd-laptop": "svec-sc-device-laptop",
        "input-keyboard-virtual-on": "svec-sc-keyboard",
        "input-keyboard-virtual-off": "svec-sc-keyboard",
        "touchpad-indicator": "svec-sc-device-tablet",
        "org.kde.plasma.pager": "svec-sc-layout-grid",
        "org.kde.plasma.folder": "svec-sc-folder",
        "user-desktop": "svec-sc-device-desktop",
        "start-here-kde": "cz.svec.Studio",
        "folder-image": "svec-sc-photo",
        "network-workgroup": "svec-sc-antenna",
        "notification-empty": "svec-sc-bell",
        "mic-muted": "svec-sc-microphone-off",
        "audio-off": "svec-sc-volume-off",
        "audio-on": "svec-sc-volume",
        "system-devices": "svec-sc-cpu",
        "system-devices-printer": "svec-sc-printer",
        "software-update-available": "svec-sc-cloud-download",
        "software-update-urgent": "svec-sc-cloud-download",
        "update-low": "svec-sc-cloud-download",
        "update-medium": "svec-sc-cloud-download",
        "update-high": "svec-sc-cloud-download",
        "update-none": "svec-kit-check",
        "chronometer": "svec-sc-timer",
        "chronometer-running": "svec-sc-timer",
        "chronometer-pause": "svec-sc-timer",
        "im-user": "svec-sc-user",
        "im-user-away": "svec-sc-moon",
        "im-user-busy": "svec-sc-minus",
        "im-user-offline": "svec-sc-user",
        "im-user-online": "svec-sc-user-check",
        "vpn": "svec-sc-shield-check",
        "locked": "svec-lock",
        "changes": "svec-sc-history",
        "state-error": "svec-sc-alert-circle",
        "state-information": "svec-sc-info-circle",
        "state-ok": "svec-kit-check",
        "state-offline": "svec-sc-wifi-off",
        "state-pause": "svec-sc-player-pause",
        "state-running": "svec-sc-activity",
        "state-sync": "svec-sc-refresh",
        "state-warning": "svec-sc-alert-triangle",
        "sync-error": "svec-sc-alert-circle",
        "sync-synchronizing": "svec-sc-refresh",
        "media-checksum-ok": "svec-kit-check",
        "media-playlist-playing": "svec-sc-player-play",
        "touchpad-disabled": "svec-sc-pointer",
        "keyboard-caps-locked": "svec-sc-keyboard",
        "input-caps-on": "svec-sc-keyboard",
        "printer-error": "svec-sc-printer",
        "printer-printing": "svec-sc-printer",
        "printer-warning": "svec-sc-printer",
        "fingerprint": "svec-sc-fingerprint",
        "installed": "svec-kit-check",
        # doplnění: tray/OSD symbolic
        "network-wired-symbolic": "svec-sc-cable",
        "network-wireless-symbolic": "svec-sc-wifi",
        "network-wireless-hotspot": "svec-sc-broadcast",
        "network-mobile-symbolic": "svec-sc-antenna",
        "brightness-high": "svec-sun",
        "brightness-low": "svec-sc-sunset",
        "brightness-medium": "svec-sun",
        "display-brightness-symbolic": "svec-sun",
        "keyboard-brightness-symbolic": "svec-sc-keyboard",
        "redshift-status-off": "svec-sc-moon-stars",
        "kdeconnect-tray": "svec-sc-device-mobile",
        "kdeconnect-tray-battery": "svec-sc-device-mobile",
        "drive-removable-media-mounted": "svec-sc-usb",
        "media-optical-mounted": "svec-sc-disc",
    },
    "emblems": {
        "emblem-shared": "svec-sc-share",
        "emblem-symbolic-link": "svec-sc-link",
        "emblem-link": "svec-sc-link",
        "emblem-important": "svec-sc-flag",
        "emblem-favorite": "svec-sc-heart",
        "emblem-default": "svec-sc-circle-check",
        "emblem-added": "svec-sc-plus",
        "emblem-remove": "svec-kit-minus",
        "emblem-checked": "svec-kit-check",
        "emblem-readonly": "svec-lock",
        "emblem-unreadable": "svec-lock",
        "emblem-locked": "svec-lock",
        "emblem-unlocked": "svec-sc-lock-open",
        "emblem-documents": "svec-sc-file-text",
        "emblem-photos": "svec-sc-photo",
        "emblem-music": "svec-sc-music",
        "emblem-videos": "svec-sc-movie",
        "emblem-downloads": "svec-sc-download",
        "emblem-downloading": "svec-sc-download",
        "emblem-system": "svec-settings",
        "emblem-web": "svec-web",
        "emblem-package": "svec-sc-package",
        "emblem-synchronizing": "svec-sc-refresh",
        "emblem-dropbox-selsync": "svec-sc-refresh",
        "emblem-dropbox-syncing": "svec-sc-refresh",
        "emblem-dropbox-uptodate": "svec-kit-check",
        "emblem-dropbox-unsyncable": "svec-sc-x",
        "emblem-mounted": "svec-sc-plug",
        "emblem-unmounted": "svec-sc-plug",
        "emblem-new": "svec-sc-sparkles",
        "emblem-information": "svec-sc-info-circle",
        "emblem-warning": "svec-sc-alert-triangle",
        "emblem-error": "svec-sc-alert-circle",
        "emblem-success": "svec-kit-check",
        "emblem-encrypted": "svec-lock",
        "emblem-insync-synced": "svec-kit-check",
        "emblem-git": "svec-sc-git-branch",
        "emblem-vcs-added": "svec-sc-plus",
        "emblem-vcs-conflicting": "svec-sc-alert-triangle",
        "emblem-vcs-locally-modified": "svec-sc-pencil",
        "emblem-vcs-locally-modified-unstaged": "svec-sc-pencil",
        "emblem-vcs-locally-modified-staged": "svec-kit-check",
        "emblem-vcs-normal": "svec-kit-check",
        "emblem-vcs-not-required": "svec-sc-minus",
        "emblem-vcs-removed": "svec-kit-minus",
        "emblem-vcs-unknown": "svec-sc-help",
        "emblem-vcs-update-required": "svec-sc-download",
        "emblem-art": "svec-sc-palette",
        "emblem-camera": "svec-sc-camera",
        "emblem-marketing": "svec-sc-megaphone",
        "emblem-money": "svec-sc-cash",
        "emblem-multimedia": "svec-sc-movie",
        "emblem-presentation": "svec-prezentace",
        "emblem-sales": "svec-sc-receipt",
        "emblem-script": "svec-sc-terminal-2",
        "emblem-text": "svec-sc-file-text",
        "emblem-development": "svec-code",
        "emblem-shared-symbolic": "svec-sc-share",
        "emblem-symbolic-link-symbolic": "svec-sc-link",
        "emblem-favorite-symbolic": "svec-sc-heart",
        "emblem-important-symbolic": "svec-sc-flag",
        "emblem-new-symbolic": "svec-sc-sparkles",
        "emblem-music-symbolic": "svec-sc-music",
    },
    "intl": {
        "preferences-desktop-locale": "svec-sc-language",
        "flag-cz": "svec-sc-flag",
        "flag-de": "svec-sc-flag",
        "flag-en": "svec-sc-flag",
    },
}

# --- kontexty "preferences" a "applets" ------------------------------------------------
# KIconLoader filtruje adresáře podle Context — KCM/plasmoid stránky žádají ikony
# z Preferences/applets kontextu; jména jen v apps/ se pak nenajdou a padá to na breeze.
FDO_MAP["preferences"] = {
    # zrcadlení všech preferences-* z apps
    **{k: v for k, v in FDO_MAP["apps"].items() if k.startswith("preferences-")},
    # breeze preferences/ jména (KCM a služby)
    "mediacontrol": "svec-sc-player-play",
    "krunner": "svec-sc-rocket",
    "plasmashell": "svec-sc-layout-dashboard",
    "plasma": "cz.svec.Studio",
    "plasma-search": "svec-sc-search",
    "plasmagik": "svec-sc-layout-dashboard",
    "kdeconnect": "svec-sc-device-mobile",
    "kded5": "svec-sc-activity",
    "kded6": "svec-sc-activity",
    "ksmserver": "svec-sc-power",
    "kaccess": "svec-sc-user",
    "device-notifier": "svec-sc-usb",
    "drive-removable-media": "svec-sc-usb",
    "gtkconfig": "svec-sc-palette",
    "kde-gtk-config": "svec-sc-palette",
    "face-smile": "svec-sc-mood-smile",
    "financial-schedule": "svec-sc-calendar",
    "podcast-amarok": "svec-sc-antenna",
}
FDO_MAP["applets"] = {
    # org.kde.plasma.* widget ikony (System Tray Settings apod.)
    "org.kde.plasma.systemtray": "svec-sc-layout-grid",
    "org.kde.plasma.mediacontroller": "svec-sc-player-play",
    "org.kde.plasma.battery": "svec-sc-bolt",
    "org.kde.plasma.brightness": "svec-sc-sun",
    "org.kde.plasma.volume": "svec-sc-volume",
    "org.kde.plasma.clipboard": "svec-sc-clipboard-list",
    "org.kde.plasma.devicenotifier": "svec-sc-usb",
    "org.kde.plasma.diskquota": "svec-sc-database",
    "org.kde.plasma.networkmanagement": "svec-sc-wifi",
    "org.kde.plasma.notifications": "svec-sc-bell",
    "org.kde.plasma.weather": "svec-sc-cloud",
    "org.kde.plasma.keyboardlayout": "svec-sc-keyboard",
    "org.kde.plasma.lockkeys": "svec-sc-keyboard",
    "org.kde.plasma.manage-inputmethod": "svec-sc-keyboard",
    "org.kde.plasma.printmanager": "svec-sc-printer",
    "org.kde.plasma.vault": "svec-sc-safe",
    "org.kde.plasma.digitalclock": "svec-sc-clock",
    "org.kde.plasma.analogclock": "svec-sc-clock",
    "org.kde.plasma.binaryclock": "svec-sc-clock",
    "org.kde.plasma.fuzzyclock": "svec-sc-clock",
    "org.kde.plasma.calendar": "svec-sc-calendar",
    "org.kde.plasma.date": "svec-sc-calendar",
    "org.kde.plasma.colorpicker": "svec-sc-color-picker",
    "org.kde.plasma.comic": "svec-sc-mood-smile",
    "org.kde.plasma.fifteenpuzzle": "svec-sc-puzzle",
    "org.kde.plasma.notes": "svec-sc-note",
    "org.kde.plasma.timer": "svec-sc-hourglass",
    "org.kde.plasma.calculator": "svec-sc-calculator",
    "org.kde.plasma.userswitcher": "svec-sc-user",
    "org.kde.plasma.lock_logout": "svec-sc-lock",
    "org.kde.plasma.minimizeall": "svec-sc-minimize",
    "org.kde.plasma.showdesktop": "svec-sc-device-desktop",
    "org.kde.plasma.showActivityManager": "svec-sc-activity",
    "org.kde.plasma.activitybar": "svec-sc-activity",
    "org.kde.plasma.systemloadviewer": "svec-sc-activity",
    "org.kde.plasma.systemmonitor.cpu": "svec-sc-cpu",
    "org.kde.plasma.systemmonitor.memory": "svec-sc-activity",
    "org.kde.plasma.systemmonitor.net": "svec-sc-wifi",
    "org.kde.plasma.systemmonitor.diskactivity": "svec-sc-database",
    "org.kde.plasma.systemmonitor.diskusage": "svec-sc-database",
    "org.kde.plasma.taskmanager": "svec-sc-list",
    "org.kde.plasma.icontasks": "svec-sc-layout-grid",
    "org.kde.plasma.windowlist": "svec-sc-layout-grid",
    "org.kde.plasma.quicklaunch": "svec-sc-rocket",
    "org.kde.plasma.kicker": "cz.svec.Studio",
    "org.kde.plasma.kickoff": "cz.svec.Studio",
    "org.kde.plasma.kickerdash": "cz.svec.Studio",
    "org.kde.plasma.kickofflegacy": "cz.svec.Studio",
    "org.kde.plasma.frame": "svec-sc-photo",
    "org.kde.plasma.folder": "svec-sc-folder",
    "org.kde.plasma.pager": "svec-sc-layout-grid",
    "org.kde.kdeconnect": "svec-sc-device-mobile",
    "org.kde.ktpcontactlist": "svec-sc-user",
    "org.kde.muonnotifier": "svec-sc-package",
}

_ENTRY_RE = re.compile(r'(?:^|,)\s*(?:(\w+)|"([^"]+)")\s*:\s*\'((?:[^\'\\]|\\.)*)\'', re.S)
_SVG_RE = re.compile(r"<svg\b([^>]*)>([\s\S]*?)</svg>")
_STRIP_ATTRS_RE = re.compile(r'\s(?:aria-hidden|width|height|id|version|class)="[^"]*"')
_VIEWBOX_RE = re.compile(r'viewBox="([^"]*)"')
_NONPAINT_RE = re.compile(r'\s(?:xmlns(?::\w+)?|viewBox)="[^"]*"')


def _js_block(text: str, marker: str) -> str:
    """Vrátí tělo `{ ... }` za `marker` (např. 'export const ICONS =')."""
    start = text.index(marker)
    brace = text.index("{", start)
    depth = 0
    i = brace
    in_str = False
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == "\\":
                i += 2
                continue
            if ch == "'":
                in_str = False
        elif ch == "'":
            in_str = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[brace + 1 : i]
        i += 1
    raise ValueError(f"neuzavřený blok za {marker!r}")


def js_svg_entries(path: Path, marker: str) -> dict[str, str]:
    """Klíč → inline SVG (nebo SVG inner) z JS objektu."""
    body = _js_block(path.read_text(encoding="utf-8"), marker)
    body = re.sub(r"/\*[\s\S]*?\*/", "", body)
    body = re.sub(r"//[^\n]*", "", body)
    out: dict[str, str] = {}
    for m in _ENTRY_RE.finditer(body):
        key = m.group(1) or m.group(2)
        val = m.group(3)
        if "<svg" in val or "<path" in val or "<circle" in val or "<rect" in val:
            out[key] = val
    return out


def split_svg(svg: str) -> tuple[str, str]:
    """(atributy <svg>, vnitřek) — normalizuje xmlns/viewBox, odstraní šum."""
    m = _SVG_RE.search(svg)
    if not m:
        raise ValueError("není SVG")
    attrs = _STRIP_ATTRS_RE.sub("", m.group(1))
    inner = m.group(2).strip()
    if "xmlns=" not in attrs:
        attrs = ' xmlns="http://www.w3.org/2000/svg"' + attrs
    if "viewBox=" not in attrs:
        attrs += ' viewBox="0 0 24 24"'
    return attrs, inner


def wrap_inner(inner: str) -> str:
    """Holý SVG inner → standardní Studio root (KIT_ICONS, syntetika)."""
    return (
        ' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"'
        ' stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"',
        inner,
    )


def _battery_inner(level: float | None, mark: str | None = None) -> str:
    """Outline baterie ve stylu Studia: tělo + hrot; level = výplň, mark = bolt/!/x."""
    parts = ['<rect x="2.5" y="8" width="17" height="9" rx="2"/>', '<path d="M22 11v3"/>']
    if level:
        w = round(13 * level, 2)
        parts.append(f'<rect x="4.5" y="10" width="{w}" height="5" rx="0.6" fill="currentColor" stroke="none"/>')
    if mark == "bolt":
        parts.append('<path d="M13 9.5l-2.7 3.6h2.1l-1.5 3.4 3.4-4.2h-2.3l1-3.4z" fill="currentColor" stroke="none"/>')
    elif mark == "exclaim":
        parts += ['<path d="M12 10v3"/>', '<path d="M12 15.2v.01"/>']
    elif mark == "cross":
        parts.append('<path d="M8 10l5 5M13 10l-5 5"/>')
    return "\n  ".join(parts)


def synth_status_icons() -> dict[str, tuple[str, str]]:
    """Tray/status ikony, které ve zdrojích chybí — baterie (Plasma naming)."""
    out: dict[str, tuple[str, str]] = {}
    for pct in range(0, 101, 10):
        name = f"battery-{pct:03d}"
        out[name] = wrap_inner(_battery_inner(pct / 100))
        out[f"{name}-charging"] = wrap_inner(_battery_inner(None, "bolt"))
    out["battery"] = wrap_inner(_battery_inner(0.7))
    out["battery-charging"] = wrap_inner(_battery_inner(None, "bolt"))
    out["battery-caution"] = wrap_inner(_battery_inner(None, "exclaim"))
    out["battery-caution-charging"] = wrap_inner(_battery_inner(None, "bolt"))
    out["battery-low"] = wrap_inner(_battery_inner(0.15))
    out["battery-low-charging"] = wrap_inner(_battery_inner(None, "bolt"))
    out["battery-full"] = wrap_inner(_battery_inner(1.0))
    out["battery-full-charged"] = wrap_inner(_battery_inner(1.0))
    out["battery-full-charging"] = wrap_inner(_battery_inner(None, "bolt"))
    out["battery-missing"] = wrap_inner(_battery_inner(None, "cross"))
    out["ups-battery"] = wrap_inner(_battery_inner(0.7))
    out["ups-charging"] = wrap_inner(_battery_inner(None, "bolt"))
    return out


# Syntetizované ikony podle kontextu (nemají svec-* zdroj — generují se přímo).
SYNTH_ICONS: dict[str, dict[str, tuple[str, str]]] = {
    "status": {},
}
SYNTH_ICONS["status"] = synth_status_icons()


def render_icon(attrs: str, inner: str, variant: str) -> str:
    if variant == "SvecStudio-Accent":
        # Vzor Breeze: class="ColorScheme-*" a stroke="currentColor" musí být
        # na STEJNÉM elementu — QtSvg resolvuje currentColor na elementu,
        # kde je stroke atribut (na rootu svg by vyšla černá).
        m = _VIEWBOX_RE.search(attrs)
        viewbox = m.group(1) if m else "0 0 24 24"
        paint = _NONPAINT_RE.sub("", attrs).strip() or 'fill="none" stroke="currentColor"'
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}">\n'
            f"  {CCS_STYLE}\n"
            f'  <g class="ColorScheme-Accent" {paint}>\n{inner}\n  </g>\n'
            f"</svg>\n"
        )
    color = WHITE if variant == "SvecStudio-White" else BLACK
    return (
        f"<svg{attrs.replace('currentColor', color)}>\n"
        f"{inner.replace('currentColor', color)}\n"
        f"</svg>\n"
    )


_CONTEXT_NAMES = {
    "apps": "Applications",
    "actions": "Actions",
    "places": "Places",
    "mimetypes": "MimeTypes",
    "devices": "Devices",
    "status": "Status",
    "emblems": "Emblems",
    "intl": "International",
    "preferences": "Preferences",
    "applets": "Applications",
}


def index_theme(theme: str, meta: dict[str, str]) -> str:
    dirs = list(dict.fromkeys(["apps", *FDO_MAP]))
    sections = [
        "[Icon Theme]",
        f"Name=Svec Studio Icons ({meta['label']})",
        f"Comment={meta['comment']} — v{meta['version']}",
        "Inherits=breeze",
        "DisplayDepth=32",
    ]
    if meta.get("follows_color_scheme"):
        sections.append("FollowsColorScheme=true")
    sections += [
        "Directories=" + ",".join(f"scalable/{d}" for d in dirs),
        "",
    ]
    for d in dirs:
        sections += [
            f"[scalable/{d}]",
            f"Context={_CONTEXT_NAMES.get(d, 'Applications')}",
            "Size=48",
            "MinSize=16",
            "MaxSize=256",
            "Type=Scalable",
            "",
        ]
    return "\n".join(sections)


def collect_icons() -> dict[str, tuple[str, str]]:
    """icon name → (svg attrs, inner); zdroj = src/<name>.svg."""
    icons: dict[str, tuple[str, str]] = {}
    for f in sorted(SRC_DIR.glob("*.svg")):
        icons[f.stem] = split_svg(f.read_text(encoding="utf-8"))
    return icons


def build_themes(out_dir: Path) -> None:
    icons = collect_icons()
    logo = LOGO_SVG.read_text(encoding="utf-8")
    missing = {src for m in FDO_MAP.values() for src in m.values() if src not in icons and src != "cz.svec.Studio"}
    if missing:
        print("VAROVÁNÍ: mapování ukazuje na neexistující ikony:", sorted(missing))
    for theme, meta in VARIANTS.items():
        theme_dir = out_dir / theme
        if theme_dir.exists():
            shutil.rmtree(theme_dir)  # jinak zůstávají zastaralé soubory z předchozích buildů
        theme_dir.mkdir(parents=True)
        (theme_dir / "index.theme").write_text(index_theme(theme, meta), encoding="utf-8")
        count = 0
        for name, (attrs, inner) in icons.items():
            f = theme_dir / "scalable" / "apps" / f"{name}.svg"
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(render_icon(attrs, inner, theme), encoding="utf-8")
            count += 1
        # logo aplikace — branding zůstává barevný ve všech variantách
        for alias in ("cz.svec.Studio", "svec-studio"):
            (theme_dir / "scalable" / "apps" / f"{alias}.svg").write_text(logo, encoding="utf-8")
            count += 1
        # standardní freedesktop jména → přebírají systémové ikony
        for ctx, mapping in FDO_MAP.items():
            ctx_dir = theme_dir / "scalable" / ctx
            ctx_dir.mkdir(parents=True, exist_ok=True)
            for fdo_name, src in mapping.items():
                fname = fdo_name.replace("/", "-")  # x-scheme-handler/magnet → x-scheme-handler-magnet.svg
                if src == "cz.svec.Studio":
                    (ctx_dir / f"{fname}.svg").write_text(logo, encoding="utf-8")
                elif src in icons:
                    attrs, inner = icons[src]
                    (ctx_dir / f"{fname}.svg").write_text(render_icon(attrs, inner, theme), encoding="utf-8")
                count += 1
        # syntetizované ikony (baterie apod. — bez svec-* zdroje)
        for ctx, synth in SYNTH_ICONS.items():
            ctx_dir = theme_dir / "scalable" / ctx
            ctx_dir.mkdir(parents=True, exist_ok=True)
            for name, (attrs, inner) in synth.items():
                (ctx_dir / f"{name}.svg").write_text(render_icon(attrs, inner, theme), encoding="utf-8")
                count += 1
        print(f"{theme}: {count} ikon → {theme_dir}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="výstupní adresář (výchozí packaging/iconpack)")
    ap.add_argument("--install", action="store_true", help="zkopírovat themy do ~/.local/share/icons/")
    args = ap.parse_args()

    build_themes(args.out)

    if args.install:
        for theme in VARIANTS:
            src = args.out / theme
            dst = INSTALL_DIR / theme
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
            print(f"installed: {dst}")
        print("\nVyber v System Settings → Icons (nebo Icons= v Plasma tématu).")


if __name__ == "__main__":
    main()
