[Icon Theme]
Name=Svec Studio Icons (White)
Comment=Outline icons from Svec Studio — fixed white — v1.1
Inherits=breeze
DisplayDepth=32
Directories=scalable/apps,scalable/places,scalable/actions,scalable/mimetypes,scalable/devices,scalable/status,scalable/emblems,scalable/intl,scalable/preferences,scalable/applets

[scalable/apps]
Context=Applications
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/places]
Context=Places
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/actions]
Context=Actions
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/devices]
Context=Devices
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/status]
Context=Status
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/emblems]
Context=Emblems
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/intl]
Context=International
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/preferences]
Context=Preferences
Size=48
MinSize=16
MaxSize=256
Type=Scalable

[scalable/applets]
Context=Applications
Size=48
MinSize=16
MaxSize=256
Type=Scalable
